// GENERATED by awf: do not edit; change .awf/ and run `awf render`
// @ts-nocheck
import { readFile } from "node:fs/promises";
import { getPackageDir, type ExtensionAPI } from "@earendil-works/pi-coding-agent";

// Retained entrypoints use this floor. The optional using_effort companion also requires active-tool APIs and the package-exported real-path file-mutation queue; Remote events remain advisory publication only.
export const MIN_PI_VERSION = "0.81.1";
const MINIMUM_RUNTIME_NOTICE = Symbol.for("awf.pi.minimum-runtime-notified");
export interface MinimumRuntimeDependencies { packageVersion: string; }
export type MinimumRuntimeAPI = "on" | "eventsOn" | "eventsEmit" | "appendEntry" | "registerTool" | "registerCommand" | "queueCommand" | "exec" | "getThinkingLevel" | "getActiveTools" | "setActiveTools";
export type MinimumRuntimeExternalAPI = "withFileMutationQueue";
function parseVersion(value: string): [number, number, number] | undefined {
  const match = /^(\d+)\.(\d+)\.(\d+)(?:[-+].*)?$/.exec(value);
  return match ? [Number(match[1]), Number(match[2]), Number(match[3])] : undefined;
}
export function versionSupported(value: string): boolean {
  const actual = parseVersion(value);
  const minimum = parseVersion(MIN_PI_VERSION)!;
  if (!actual) return false;
  for (let i = 0; i < minimum.length; i++) {
    if (actual[i] !== minimum[i]) return actual[i] > minimum[i];
  }
  return true;
}
export function guardMinimumRuntime(pi: ExtensionAPI, deps: MinimumRuntimeDependencies, required: readonly MinimumRuntimeAPI[]): boolean {
  const requirements: Record<MinimumRuntimeAPI, boolean> = {
    on: typeof pi.on === "function", eventsOn: typeof pi.events?.on === "function", eventsEmit: typeof pi.events?.emit === "function",
    appendEntry: typeof pi.appendEntry === "function", registerTool: typeof pi.registerTool === "function", registerCommand: typeof pi.registerCommand === "function",
    queueCommand: typeof pi.queueCommand === "function", exec: typeof pi.exec === "function", getThinkingLevel: typeof pi.getThinkingLevel === "function", getActiveTools: typeof pi.getActiveTools === "function", setActiveTools: typeof (pi as any).setActiveTools === "function",
  };
  const missing = required.filter((name) => !requirements[name]);
  if (versionSupported(deps.packageVersion) && missing.length === 0) return true;
  if (typeof pi.on !== "function") return false;
  pi.on("session_start", async (_event, ctx) => {
    if ((globalThis as any)[MINIMUM_RUNTIME_NOTICE]) return;
    (globalThis as any)[MINIMUM_RUNTIME_NOTICE] = true;
    const missingAPI = missing.length > 0 ? ` Missing runtime APIs: ${missing.join(", ")}.` : "";
    ctx.ui.notify(`awf Pi extensions require Pi ${MIN_PI_VERSION} or newer with their factory event, persistence, tool, command, process, and thinking APIs; found ${deps.packageVersion}.${missingAPI} Upgrade Pi and reload.`, "error");
  });
  return false;
}

export function formatCount(value:number):string {
  if (value < 1000) return String(Math.round(value));
  if (value < 1000000) return `${(value / 1000).toFixed(1).replace(/\.0$/, "")}k`;
  return `${(value / 1000000).toFixed(1).replace(/\.0$/, "")}m`;
}

export function contextUsageLine(ctx:any):string {
  const usage=ctx.getContextUsage();
  const compactions=ctx.sessionManager.getBranch().filter((entry:any)=>entry.type==="compaction").length;
  const window=usage?.contextWindow;
  if (!Number.isFinite(window)||window<=0) return `[session context] unavailable; compactions=${compactions}`;
  const tokens=usage?.tokens;
  if (!Number.isFinite(tokens)) return `[session context] unknown/${formatCount(window)}; compactions=${compactions}`;
  return `[session context] ${formatCount(tokens)}/${formatCount(window)} (${Math.round(tokens/window*100)}%); compactions=${compactions}`;
}

export function registerContextUsage(pi:ExtensionAPI,deps:MinimumRuntimeDependencies):void {
  if (!guardMinimumRuntime(pi,deps,["on"])) return;
  pi.on("context",(event:any,ctx:any)=>({messages:[...event.messages,{role:"custom",customType:"awf-context-usage",content:contextUsageLine(ctx),display:false,timestamp:Date.now()}]}));
}

export default async function(pi:ExtensionAPI):Promise<void> {
  const pkg=JSON.parse(await readFile(`${getPackageDir()}/package.json`,"utf8"));
  registerContextUsage(pi,{packageVersion:pkg.version});
}
