// GENERATED by awf: do not edit; change .awf/ and run `awf render`
// @ts-nocheck
import { randomUUID } from "node:crypto";
import { readFile, stat } from "node:fs/promises";
import { join } from "node:path";
import { Type } from "typebox";
import * as codingAgentRuntime from "@earendil-works/pi-coding-agent";
import { renderDiff } from "@earendil-works/pi-coding-agent";
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Box, Container, Spacer, Text } from "@earendil-works/pi-tui";
import { activity, memoryRead, memoryEdit, memoryUpdate, childMemoryExecutor, type ActivityExecutor, type ActivityReply, type MemoryDiff, type MemoryExecutor, type MemoryOutcome, type MemoryReply } from "./client.ts";
// Retained entrypoints use this floor. The optional using_effort companion also requires active-tool APIs and the package-exported real-path file-mutation queue; Remote events remain advisory publication only.
export const MIN_PI_VERSION = "0.84.2";
const MINIMUM_RUNTIME_NOTICE = Symbol.for("awf.pi.minimum-runtime-notified");
export interface MinimumRuntimeDependencies { packageVersion: string; }
export type MinimumRuntimeAPI = "on" | "eventsOn" | "eventsEmit" | "appendEntry" | "registerTool" | "registerCommand" | "queueCommand" | "exec" | "getThinkingLevel" | "getActiveTools" | "setActiveTools";
export type MinimumRuntimeExternalAPI = "withFileMutationQueue";
function parseVersion(value: string): [number, number, number] | undefined {
  const match = /^(\d+)\.(\d+)\.(\d+)(?:[-+].*)?$/.exec(value);
  return match ? [Number(match[1]), Number(match[2]), Number(match[3])] : undefined;
}
export function versionSupported(value: string): boolean {
  const actual = parseVersion(value);
  const minimum = parseVersion(MIN_PI_VERSION)!;
  if (!actual) return false;
  for (let i = 0; i < minimum.length; i++) {
    if (actual[i] !== minimum[i]) return actual[i] > minimum[i];
  }
  return true;
}
export function guardMinimumRuntime(pi: ExtensionAPI, deps: MinimumRuntimeDependencies, required: readonly MinimumRuntimeAPI[]): boolean {
  const requirements: Record<MinimumRuntimeAPI, boolean> = {
    on: typeof pi.on === "function", eventsOn: typeof pi.events?.on === "function", eventsEmit: typeof pi.events?.emit === "function",
    appendEntry: typeof pi.appendEntry === "function", registerTool: typeof pi.registerTool === "function", registerCommand: typeof pi.registerCommand === "function",
    queueCommand: typeof pi.queueCommand === "function", exec: typeof pi.exec === "function", getThinkingLevel: typeof pi.getThinkingLevel === "function", getActiveTools: typeof pi.getActiveTools === "function", setActiveTools: typeof (pi as any).setActiveTools === "function",
  };
  const missing = required.filter((name) => !requirements[name]);
  if (versionSupported(deps.packageVersion) && missing.length === 0) return true;
  if (typeof pi.on !== "function") return false;
  pi.on("session_start", async (_event, ctx) => {
    if ((globalThis as any)[MINIMUM_RUNTIME_NOTICE]) return;
    (globalThis as any)[MINIMUM_RUNTIME_NOTICE] = true;
    const missingAPI = missing.length > 0 ? ` Missing runtime APIs: ${missing.join(", ")}.` : "";
    ctx.ui.notify(`awf Pi extensions require Pi ${MIN_PI_VERSION} or newer with their factory event, persistence, tool, command, process, and thinking APIs; found ${deps.packageVersion}.${missingAPI} Upgrade Pi and reload.`, "error");
  });
  return false;
}

const SLUG = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
const MEMORY_TOOL_NAMES = ["effort_memory_read", "effort_memory_edit", "effort_memory_update"] as const;
const MUTATION_TRUNCATION_NOTICE = "Diff truncated for display.";
const PREVIEW_ENTRY_LIMIT = 32;
type MutationStatus = "pending" | "settled" | "failed";
type MutationRow = Box & { key: string | undefined; request: string | undefined; body: string | undefined; truncated: boolean; status: MutationStatus; authoritative: boolean };
type MutationSpec = Readonly<{ name: string; label: string; description: string; parameters: unknown; promptSnippet: string; promptGuidelines: readonly string[]; title: string; key: (args: any) => string | undefined; check: (args: any) => void; invoke: (snapshot: Snapshot, cwd: string, args: any, preview: boolean, signal?: AbortSignal) => Promise<MemoryReply> }>;
type Snapshot = Readonly<{ slug: string; owner: string; title: string; memory: Readonly<{ phase: string; next: string; updated: string }> | null; heartbeatAt: string; managedWorktree: boolean }>;
type Context = { cwd: string };
type FileMutationQueue = <T>(path: string, work: () => Promise<T>) => Promise<T>;
export type PiCockpitMetadata = Readonly<{ effort: Readonly<{ slug: string; title: string }>; memory: Snapshot["memory"]; activity: Readonly<{ heartbeatAt: string }> }>;
export type PiCockpitMetadataSetPayload = Readonly<{ namespace: "awf"; value: PiCockpitMetadata | null }>;
export type PiCockpitDisplaySuffixSetPayload = Readonly<{ value: string | null }>;
export type PiCockpitCapabilitiesReplyPayload = Readonly<{ displaySuffix?: unknown; [capability: string]: unknown }>;
type PiLike = { exec: ActivityExecutor; registerTool(tool: unknown): void; on?(name: string, handler: (event: any, ctx: Context) => any): void; events?: { emit(name: string, payload?: unknown): unknown; on?(name: string, handler: (payload: any, ctx?: Context) => void): unknown }; getActiveTools?(): readonly string[]; setActiveTools?(tools: string[]): void };
export type EffortExtensionDependencies = Readonly<{ uuid?: () => string; isDirectory?: (path: string) => Promise<boolean>; packageVersion?: string; memoryExec?: MemoryExecutor; fileMutationQueue?: FileMutationQueue }>;

function supportsDisplaySuffix(caps: PiCockpitCapabilitiesReplyPayload | unknown): boolean { if (!caps || typeof caps !== "object") return false; const suffix = (caps as Record<string, unknown>).displaySuffix; if (!suffix || typeof suffix !== "object" || Array.isArray(suffix)) return false; const keys = Object.keys(suffix); return keys.length === 1 && keys[0] === "version" && (suffix as Record<string, unknown>).version === 1; }
function immutable(reply: ActivityReply, owner: string, present: boolean): Snapshot | undefined { if (!reply.effort || !reply.memory || !reply.activity || reply.activity.owner !== owner) return; return Object.freeze({ slug: reply.effort.slug, owner, title: reply.effort.title, memory: Object.freeze({ phase: reply.memory.phase, next: reply.memory.next, updated: reply.memory.updated }), heartbeatAt: reply.activity.heartbeatAt, managedWorktree: present }); }
function renderActivity(reply: ActivityReply): string { const outcome = reply.outcome!; const actions = outcome.nextActions.length === 1 ? outcome.nextActions[0] : outcome.nextActions.map((action, index) => `${index + 1}. ${action}`).join(" "); return `${outcome.category}; ${outcome.condition}; changedActivity=${outcome.changedActivity}${outcome.cause ? `; cause=${outcome.cause}` : ""}; ${actions}`; }
function renderMemoryOutcome(outcome: MemoryOutcome): string { const actions = outcome.nextActions.length === 1 ? outcome.nextActions[0] : outcome.nextActions.map((action, index) => `${index + 1}. ${action}`).join(" "); return `${outcome.category}; ${outcome.condition}; changedMemory=${outcome.changedMemory}${outcome.cause ? `; cause=${outcome.cause}` : ""}; ${actions}`; }
function memoryResult(reply: MemoryReply): { content: { type: "text"; text: string }[]; details: MemoryReply } { const text = reply.condition === "read" ? reply.content! : reply.condition === "edited" ? `Replaced ${reply.replacementCount} block(s) in effort memory.` : reply.condition === "updated" ? "Memory metadata updated." : renderMemoryOutcome(reply.outcome!); return { content: [{ type: "text", text }], details: reply }; }
function mutationRow(state: any, lastComponent: unknown): MutationRow { if (lastComponent instanceof Box) { state.callComponent = lastComponent; return lastComponent as MutationRow; } if (state.callComponent) return state.callComponent as MutationRow; const row = Object.assign(new Box(1, 1), { key: undefined as string | undefined, request: undefined as string | undefined, body: undefined as string | undefined, truncated: false, status: "pending" as MutationStatus, authoritative: false }); state.callComponent = row; return row; }
function mutationBackground(status: MutationStatus, theme: any): (value: string) => string { if (status === "failed") return (value: string) => theme.bg("toolErrorBg", value); if (status === "pending") return (value: string) => theme.bg("toolPendingBg", value); return (value: string) => theme.bg("toolSuccessBg", value); }
function buildMutationRow(row: MutationRow, title: string, theme: any): MutationRow { row.setBgFn(mutationBackground(row.status, theme)); row.clear(); row.addChild(new Text(theme.fg("toolTitle", theme.bold(title)), 0, 0)); if (row.body !== undefined) { row.addChild(new Spacer(1)); row.addChild(new Text(row.body, 0, 0)); } if (row.truncated) { row.addChild(new Spacer(1)); row.addChild(new Text(theme.fg("warning", MUTATION_TRUNCATION_NOTICE), 0, 0)); } return row; }
// The binary terminates every display row, while renderDiff splits an unterminated block; the sole trailing terminator would otherwise render as a stray context line.
function showMutationDiff(row: MutationRow, diff: MemoryDiff): void { const text = diff.text.endsWith("\n") ? diff.text.slice(0, -1) : diff.text; const body = text === "" ? undefined : renderDiff(text); row.status = "settled"; row.body = body; row.truncated = diff.truncated; }
function showMutationFailure(row: MutationRow, message: string, theme: any): void { row.status = "failed"; row.body = theme.fg("error", message); row.truncated = false; }
function mutationResultText(result: any): string { return result.content.map((block: any) => block.text).join("\n"); }
function guardEffortFileQueue(pi: PiLike, packageVersion: string, queue: FileMutationQueue | undefined): boolean { if (typeof queue === "function") return true; if (typeof pi.on !== "function") return false; pi.on("session_start", async (_event, ctx: any) => { if ((globalThis as any)[MINIMUM_RUNTIME_NOTICE]) return; (globalThis as any)[MINIMUM_RUNTIME_NOTICE] = true; ctx.ui.notify(`awf Pi extensions require Pi ${MIN_PI_VERSION} or newer with their factory event, persistence, tool, command, process, and thinking APIs; found ${packageVersion}. Missing runtime APIs: withFileMutationQueue. Upgrade Pi and reload.`, "error"); }); return false; }

export function registerEffort(pi: PiLike, deps: EffortExtensionDependencies = {}): void {
  const packageVersion = deps.packageVersion ?? "unknown";
  if (!guardEffortFileQueue(pi, packageVersion, deps.fileMutationQueue)) return;
  if (!guardMinimumRuntime(pi as unknown as ExtensionAPI, { packageVersion }, ["on", "registerTool", "exec", "getActiveTools", "setActiveTools"])) return;
  const uuid = deps.uuid ?? randomUUID; const owner = uuid(); const directory = deps.isDirectory ?? (async (path) => { try { return (await stat(path)).isDirectory(); } catch { return false; } }); const fileMutationQueue = deps.fileMutationQueue!;
  if (!/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/.test(owner)) throw new Error("extension owner must be a lowercase UUIDv4");
  let current: Snapshot | undefined; let suffixSupported = false; let chain = Promise.resolve();
  const emit = (name: string, payload?: unknown) => { try { pi.events?.emit(name, payload); } catch {} };
  const publishSuffix = () => { const payload: PiCockpitDisplaySuffixSetPayload = { value: suffixSupported && current ? current.slug : null }; emit("pi-cockpit:display-suffix:set", payload); };
  const publish = () => { const snapshot = current; const payload: PiCockpitMetadataSetPayload = { namespace: "awf", value: snapshot ? { effort: { slug: snapshot.slug, title: snapshot.title }, memory: snapshot.memory, activity: { heartbeatAt: snapshot.heartbeatAt } } : null }; emit("pi-cockpit:metadata:set", payload); publishSuffix(); };
  const requestCapabilities = () => emit("pi-cockpit:capabilities:request");
  const serial = <T>(work: () => Promise<T>): Promise<T> => { const run = chain.then(work, work); chain = run.then(() => undefined, () => undefined); return run; };
  const activate = (on: boolean) => { const existing = pi.getActiveTools!().filter((name) => !MEMORY_TOOL_NAMES.includes(name as typeof MEMORY_TOOL_NAMES[number])); pi.setActiveTools!(on ? [...new Set([...existing, ...MEMORY_TOOL_NAMES])] : existing); };
  const clear = () => { current = undefined; activate(false); publish(); };
  const invoke = (ctx: Context, operation: "attach" | "heartbeat" | "detach", slug: string, invocationOwner: string, signal?: AbortSignal) => activity(pi.exec, ctx.cwd, operation, slug, invocationOwner, signal);
  const detach = async (ctx: Context, signal?: AbortSignal): Promise<string> => { if (!current) { clear(); return "Detached."; } const before = current; const reply = await invoke(ctx, "detach", before.slug, before.owner, signal); clear(); return reply.condition === "detached" || reply.condition === "missing" || reply.condition === "not-owner" ? "Detached." : renderActivity(reply); };
  const memoryExecutor: MemoryExecutor = deps.memoryExec ?? ((command, argv, options) => options.stdin === undefined ? pi.exec(command, argv, options) : childMemoryExecutor(command, argv, options));
  const memoryCall = async (ctx: Context, signal: AbortSignal, operation: (snapshot: Snapshot) => Promise<MemoryReply>, mutate = false) => serial(async () => { const snapshot = current; if (!snapshot) throw new Error("Attach an effort before using its memory tools"); const run = async () => { const reply = await operation(snapshot); if (reply.condition === "not-owner" || reply.condition === "missing" || reply.condition === "unsafe-activity") clear(); return memoryResult(reply); }; return mutate ? fileMutationQueue(join(ctx.cwd, ".awf", "efforts", snapshot.slug, "memory.md"), run) : run(); });
  const previews = new Map<string, { key: string; cwd: string; reply: Promise<MemoryReply> }>();
  const associationKey = (value: unknown): string | undefined => { const snapshot = current; return snapshot ? JSON.stringify({ slug: snapshot.slug, owner: snapshot.owner, value }) : undefined; };
  // A call rendered but never executed never settles, so bound the map by insertion order; a dropped entry only costs the recomputation execute already performs when no renderer ran.
  const previewCall = (toolCallId: string, key: string, cwd: string, invoke: (snapshot: Snapshot) => Promise<MemoryReply>): Promise<MemoryReply> => { const existing = previews.get(toolCallId); if (existing && existing.key === key && existing.cwd === cwd) return existing.reply; const reply = serial(async () => { const snapshot = current; if (!snapshot) throw new Error("Attach an effort before using its memory tools"); const preview = await invoke(snapshot); if (preview.condition === "not-owner" || preview.condition === "missing" || preview.condition === "unsafe-activity") clear(); if (preview.condition !== "previewed") throw new Error(renderMemoryOutcome(preview.outcome!)); return preview; }); previews.set(toolCallId, { key, cwd, reply }); if (previews.size > PREVIEW_ENTRY_LIMIT) previews.delete(previews.keys().next().value as string); return reply; };
  // Pi wraps its synchronous renderers, but an asynchronous preview callback owns its own failures; an escaping throw here would be an unhandled rejection rather than a redrawn row.
  // A preview is only ever provisional, so an authoritative result latches the row: a preview resolving afterwards must not repaint a pre-mutation diff over it.
  const settlePreview = (row: MutationRow, key: string, title: string, theme: any, context: any, apply: () => void): void => { if (row.key !== key || row.authoritative) return; try { apply(); buildMutationRow(row, title, theme); context.invalidate(); } catch { /* leave the row as drawn; the next redraw rebuilds it */ } };
  const registerMutation = (spec: MutationSpec) => pi.registerTool({
    name: spec.name, label: spec.label, description: spec.description, parameters: spec.parameters, promptSnippet: spec.promptSnippet, promptGuidelines: spec.promptGuidelines, renderShell: "self",
    execute: async (toolCallId: string, args: any, signal: AbortSignal, _update: unknown, ctx: Context) => { spec.check(args); try { await previewCall(toolCallId, spec.key(args) ?? "", ctx.cwd, (snapshot) => spec.invoke(snapshot, ctx.cwd, args, true, signal)); return await memoryCall(ctx, signal, (snapshot) => spec.invoke(snapshot, ctx.cwd, args, false, signal), true); } finally { previews.delete(toolCallId); } },
    renderCall: (args: any, theme: any, context: any) => {
      const row = mutationRow(context.state, context.lastComponent);
      const key = context.argsComplete ? spec.key(args) : undefined;
      if (row.key !== key) { row.key = key; row.request = undefined; row.body = undefined; row.truncated = false; row.status = "pending"; row.authoritative = false; }
      if (key !== undefined && row.request === undefined && !context.executionStarted) {
        row.request = key;
        void previewCall(context.toolCallId, key, context.cwd, (snapshot) => spec.invoke(snapshot, context.cwd, args, true)).then(
          (preview) => settlePreview(row, key, spec.title, theme, context, () => showMutationDiff(row, preview.diff!)),
          (error: Error) => settlePreview(row, key, spec.title, theme, context, () => showMutationFailure(row, error.message, theme)),
        );
      }
      return buildMutationRow(row, spec.title, theme);
    },
    renderResult: (result: any, _options: any, theme: any, context: any) => {
      const row = context.state.callComponent as MutationRow | undefined;
      if (row) { row.authoritative = true; const reply = context.isError ? undefined : result.details as MemoryReply | undefined; if (reply && reply.diff) showMutationDiff(row, reply.diff); else showMutationFailure(row, mutationResultText(result), theme); buildMutationRow(row, spec.title, theme); }
      const component = context.lastComponent ?? new Container(); component.clear(); return component;
    },
  });

  pi.registerTool({ name: "using_effort", label: "Use effort", description: "Explicitly attach or detach this Pi session from an effort without changing CWD.", parameters: Type.Object({ effort: Type.Optional(Type.String({ minLength: 1, maxLength: 63 })), detach: Type.Optional(Type.Boolean()) }, { additionalProperties: false }), execute: async (_id: string, args: { effort?: string; detach?: boolean }, signal: AbortSignal, onUpdate: unknown, ctx: Context) => serial(async () => { void onUpdate; if (!Object.keys(args).every((key) => key === "effort" || key === "detach") || (args.detach === true) === (args.effort !== undefined)) throw new Error("supply exactly one of effort or detach"); if (args.detach === true) return { content: [{ type: "text", text: await detach(ctx, signal) }] }; if (!SLUG.test(args.effort!)) throw new Error("effort must be a canonical slug"); if (current && current.slug !== args.effort) await detach(ctx, signal); const reply = await invoke(ctx, "attach", args.effort!, owner, signal); if (reply.condition !== "attached" && reply.condition !== "taken-over") return { content: [{ type: "text", text: renderActivity(reply) }] }; const present = await directory(join(ctx.cwd, ".awf", "worktrees", args.effort!)).catch(() => false); const next = immutable(reply, owner, present); if (!next) throw new Error("awf returned an incomplete attached reply"); current = next; activate(true); publish(); return { content: [{ type: "text", text: `Attached to ${next.slug}.` }] }; }) });
  pi.registerTool({ name: "effort_memory_read", label: "Read effort memory", description: "Read the associated effort memory.", parameters: Type.Object({ offset: Type.Optional(Type.Integer({ minimum: 1 })), limit: Type.Optional(Type.Integer({ minimum: 1 })) }, { additionalProperties: false }), promptSnippet: "Read associated effort memory.", promptGuidelines: ["Prefer effort_memory_read for pathless reads of the associated effort memory; generic file tools remain available."], execute: async (_id: unknown, args: { offset?: number; limit?: number }, signal: AbortSignal, _update: unknown, ctx: Context) => memoryCall(ctx, signal, (snapshot) => memoryRead(memoryExecutor, ctx.cwd, snapshot.slug, snapshot.owner, args, signal)) });
  registerMutation({ name: "effort_memory_edit", label: "Edit effort memory", description: "Exactly edit only the associated memory Markdown body.", parameters: Type.Object({ edits: Type.Array(Type.Object({ oldText: Type.String({ minLength: 1, maxLength: 1048576 }), newText: Type.String({ maxLength: 1048576 }) }, { additionalProperties: false }), { minItems: 1, maxItems: 128 }) }, { additionalProperties: false }), promptSnippet: "Edit the associated memory body.", promptGuidelines: ["Prefer effort_memory_edit for exact Markdown body edits; use effort_memory_update for phase or next, and rely on automatic timestamps. Generic file tools remain available."], title: "edit memory", check: () => {}, key: (args: any) => (args && Array.isArray(args.edits) && args.edits.length > 0 ? associationKey({ edits: args.edits }) : undefined), invoke: (snapshot, cwd, args, preview, signal) => memoryEdit(memoryExecutor, cwd, snapshot.slug, snapshot.owner, args.edits, signal, { preview }) });
  registerMutation({ name: "effort_memory_update", label: "Update effort memory", description: "Update associated effort phase or next metadata.", parameters: Type.Object({ phase: Type.Optional(Type.String({ minLength: 1, maxLength: 500 })), next: Type.Optional(Type.String({ minLength: 1, maxLength: 500 })) }, { additionalProperties: false }), promptSnippet: "Update associated effort memory metadata.", promptGuidelines: ["Prefer effort_memory_update for phase or next metadata, separately from effort_memory_edit body changes, and rely on automatic timestamps. Generic file tools remain available."], title: "update memory", check: (args: any) => { if (args.phase === undefined && args.next === undefined) throw new Error("supply phase or next"); }, key: (args: any) => (args && (typeof args.phase === "string" || typeof args.next === "string") ? associationKey({ phase: args.phase ?? null, next: args.next ?? null }) : undefined), invoke: (snapshot, cwd, args, preview, signal) => memoryUpdate(memoryExecutor, cwd, snapshot.slug, snapshot.owner, args, signal, { preview }) });
  pi.on?.("context", (event: any) => { if (!current) return; const snapshot = current; return { messages: [...event.messages, { role: "custom", customType: "awf-effort", content: `[awf effort] active=${snapshot.slug} memory=.awf/efforts/${snapshot.slug}/memory.md${snapshot.managedWorktree ? ` managedWorktree=.awf/worktrees/${snapshot.slug}` : ""}`, display: false, timestamp: Date.now() }] }; });
  pi.on?.("turn_end", (_event: any, ctx: Context) => serial(async () => { if (!current) return; const before = current; try { const reply = await invoke(ctx, "heartbeat", before.slug, before.owner); if (reply.condition === "not-owner" || reply.condition === "missing" || reply.condition === "unsafe-resident") { clear(); return; } if (reply.condition !== "heartbeat") { current = Object.freeze({ ...before, memory: null, managedWorktree: false }); publish(); return; } const present = await directory(join(ctx.cwd, ".awf", "worktrees", before.slug)).catch(() => false); current = immutable(reply, before.owner, present) ?? Object.freeze({ ...before, memory: null, managedWorktree: false }); publish(); } catch { current = Object.freeze({ ...before, memory: null, managedWorktree: false }); publish(); } }));
  pi.on?.("session_start", () => { clear(); requestCapabilities(); });
  pi.on?.("session_shutdown", (_event: any, ctx: Context) => serial(async () => { try { await detach(ctx); } catch { clear(); } }));
  pi.events?.on?.("pi-cockpit:metadata:request", () => publish());
  pi.events?.on?.("pi-cockpit:display-suffix:request", () => publishSuffix());
  pi.events?.on?.("pi-cockpit:capabilities", (caps: PiCockpitCapabilitiesReplyPayload) => { suffixSupported = supportsDisplaySuffix(caps); publishSuffix(); });
  requestCapabilities();
}

export async function registerDefaultEffort(pi: PiLike, runtime: Record<string, unknown>, read: typeof readFile = readFile): Promise<void> {
  let packageVersion = "unknown";
  try { const packageDirectory = typeof runtime.getPackageDir === "function" ? runtime.getPackageDir() : ""; const pkg = JSON.parse(await read(`${packageDirectory}/package.json`, "utf8")); packageVersion = typeof pkg.version === "string" ? pkg.version : "unknown"; } catch {}
  registerEffort(pi, { packageVersion, fileMutationQueue: typeof runtime.withFileMutationQueue === "function" ? runtime.withFileMutationQueue as FileMutationQueue : undefined });
}

export default async function effortExtension(pi: PiLike): Promise<void> {
  await registerDefaultEffort(pi, codingAgentRuntime);
}
