#!/usr/bin/env bash
# GENERATED by awf: do not edit; change .awf/ and run `awf render`
# Fetches and verifies a pinned awf binary, caches it, and prints its path.
# A pre-set AWF_VERSION overrides which release is fetched (the upgrade
# porcelain relies on this); absent one, the pin resolves. Stdout carries
# exactly one line, the resolved binary path; every diagnostic goes to
# stderr.
set -euo pipefail

AWF_VERSION="${AWF_VERSION:-0.45.0}"
REPO="hypnotox/agentic-workflows"

# Local-first: an awf on PATH reporting exactly the pinned version wins over
# any download.
if command -v awf >/dev/null 2>&1; then
  local_version="$(awf version 2>/dev/null | awk '
    /^version: [^[:space:]()]+( \([^[:cntrl:]]+\))?$/ {
      if (found) { bad = 1; exit }
      found = 1
      value = substr($0, 10)
      sub(/ \(.*/, "", value)
      next
    }
    { bad = 1; exit }
    END { if (!bad && found == 1) print value; else exit 1 }
  ' || true)"
  if [ "${local_version}" = "${AWF_VERSION}" ]; then
    command -v awf
    exit 0
  fi
fi

os="$(uname -s | tr '[:upper:]' '[:lower:]')"
arch="$(uname -m)"
case "$arch" in
  x86_64|amd64) arch="amd64" ;;
  arm64|aarch64) arch="arm64" ;;
  *) echo "awf bootstrap: unsupported arch: $arch; install manually: https://github.com/${REPO}#install" >&2; exit 1 ;;
esac
case "$os" in
  linux|darwin) ;;
  *) echo "awf bootstrap: unsupported os: $os; install manually: https://github.com/${REPO}#install" >&2; exit 1 ;;
esac

cache_dir="${XDG_CACHE_HOME:-$HOME/.cache}/awf/${AWF_VERSION}"
binary="${cache_dir}/awf"
if [ -x "$binary" ]; then
  echo "$binary"
  exit 0
fi

asset="awf_${AWF_VERSION}_${os}_${arch}.tar.gz"
base="https://github.com/${REPO}/releases/download/v${AWF_VERSION}"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

curl -fsSL "${base}/${asset}" -o "${tmp}/${asset}"
curl -fsSL "${base}/checksums.txt" -o "${tmp}/checksums.txt"

if command -v sha256sum >/dev/null 2>&1; then
  (cd "$tmp" && grep " ${asset}\$" checksums.txt | sha256sum -c - >&2)
else
  (cd "$tmp" && grep " ${asset}\$" checksums.txt | shasum -a 256 -c - >&2)
fi

tar -xzf "${tmp}/${asset}" -C "$tmp"
mkdir -p "$cache_dir"
install -m 0755 "${tmp}/awf" "$binary"
echo "$binary"
