#!/usr/bin/env bash
# GENERATED by awf: do not edit; change .awf/ and run `awf render`
# Upgrades this project's awf with one command: resolves the target version
# ($1, or the newest GitHub release), fetches and verifies it via
# .awf/bootstrap.sh, then hands off to `awf upgrade`, which migrates the
# config, re-renders every managed file, and re-pins the bootstrap.
# Deliberately nondeterministic porcelain for humans; CI and hooks call the
# deterministic .awf/bootstrap.sh instead.
#
# This porcelain runs the ordinary `awf upgrade`, which migrates the schema or,
# when the lock carries a bridge attestation, consumes that seal as the final
# current-state cutover. Recovering an interrupted cutover is `awf upgrade
# --recover`. Attestation lives only in the preceding bridge release; this binary
# consumes seals, it never produces them.
set -euo pipefail

REPO="hypnotox/agentic-workflows"
cd "$(dirname "$0")/.."

if [ "$#" -gt 0 ]; then
  target="${1#v}"
else
  latest_url="$(curl -fsSLI -o /dev/null -w '%{url_effective}' "https://github.com/${REPO}/releases/latest")"
  case "$latest_url" in
    */tag/*) target="${latest_url##*/tag/}"; target="${target#v}" ;;
    *) echo "awf upgrade.sh: could not resolve the latest release from ${latest_url}" >&2; exit 1 ;;
  esac
fi
# An empty target (e.g. an unset variable passed as $1) would make the
# bootstrap's default expansion silently re-fetch the current pin.
[ -n "${target}" ] || { echo "awf upgrade.sh: empty target version" >&2; exit 1; }
echo "awf upgrade.sh: upgrading to ${target}" >&2

binary="$(AWF_VERSION="$target" bash .awf/bootstrap.sh)"

# exec is load-bearing, not style: `awf upgrade` rewrites this script in
# place, and replacing the shell process first makes that rewrite safe.
exec "$binary" upgrade
