#!/usr/bin/env bash
# GENERATED by awf: do not edit; change .awf/ and run `awf render`
# Commit-msg payload: deterministic Conventional Commits validation. Inert until wired
# into a hook setup you own, e.g. a .git/hooks/commit-msg stub containing:
#   exec bash .awf/hooks/commit-msg.sh "$@"
set -euo pipefail
./awf check staged commit "$1"
