#!/usr/bin/env bash
# GENERATED by awf: do not edit; change .awf/ and run `awf render`
# Pre-push payload: validates only the commits introduced by pushed ref updates
# against the optional commit policy before running the fullest configured gate.
# Inert until wired into a hook setup you own. A stub resolves the invoking
# worktree before delegating:
#   repo_root=$(git rev-parse --show-toplevel) || exit 1
#   exec bash "$repo_root/.awf/hooks/pre-push.sh" "$@"
set -euo pipefail

root="$(git rev-parse --show-toplevel)"
cd "$root"
empty_oid="$(git hash-object -t blob --stdin </dev/null)"
zero_oid="${empty_oid//?/0}"
hook_remote_url="${2:-}"
integration_branch_hex='6d61696e'
integration_branch=
while [[ -n "$integration_branch_hex" ]]; do
  printf -v integration_branch_byte '%b' "\\x${integration_branch_hex:0:2}"
  integration_branch+="$integration_branch_byte"
  integration_branch_hex="${integration_branch_hex:2}"
done
integration_ref="refs/heads/$integration_branch"
integration_tip=
updates=()
while IFS= read -r update || [[ -n "$update" ]]; do updates+=("$update"); done
policy_targets=()
ranges=()

refusal() {
  printf 'commit policy refused: %s\n' "$1" >&2
  printf '%s\n' 'nothing was pushed; reconcile the local object and commit policy, then retry the complete push' >&2
  exit 1
}

add_policy_target() {
  local target
  for target in "${policy_targets[@]+"${policy_targets[@]}"}"; do [[ "$target" != "$1" ]] || return 0; done
  policy_targets+=("$1")
}

peel_commit_target() {
  local source="$1"
  local object="$2"
  local type
  peeled_object=
  type="$(git cat-file -t "$object" 2>/dev/null)" || refusal "$source names missing object $object"
  if [[ "$type" == tag ]]; then
    object="$(git rev-parse --verify "$object^{}" 2>/dev/null)" || refusal "$source cannot be peeled"
    type="$(git cat-file -t "$object" 2>/dev/null)" || refusal "$source peels to missing object $object"
  fi
  if [[ "$type" == commit ]]; then
    peeled_object="$object"
    return 0
  fi
  printf 'commit policy note: %s resolves to non-commit %s %s; no commit added\n' "$source" "$type" "$object" >&2
  return 1
}

resolve_integration_tip() {
  [[ -n "$integration_tip" ]] && return
  [[ -n "$hook_remote_url" && -n "$integration_branch" ]] || refusal "cannot resolve destination integration branch $integration_ref"
  local record oid ref extra
  record="$(git ls-remote --exit-code "$hook_remote_url" "$integration_ref" 2>/dev/null)" || refusal "cannot resolve destination integration branch $integration_ref"
  [[ "$record" != *$'\n'* ]] || refusal "destination integration branch $integration_ref returned ambiguous evidence"
  IFS=$'\t' read -r oid ref extra <<< "$record"
  [[ -n "${oid:-}" && "$ref" == "$integration_ref" && -z "${extra:-}" ]] || refusal "destination integration branch $integration_ref returned malformed evidence"
  [[ "$oid" =~ ^[[:xdigit:]]+$ && ${#oid} -eq ${#zero_oid} && "$oid" != "$zero_oid" ]] || refusal "destination integration branch $integration_ref returned malformed object ID"
  git rev-parse --verify "$oid^{commit}" >/dev/null 2>&1 || refusal "destination integration branch $integration_ref names unresolvable commit $oid"
  integration_tip="$oid"
}

for update in "${updates[@]+"${updates[@]}"}"; do
  IFS=' ' read -r local_ref local_oid remote_ref remote_oid extra <<< "$update"
  if [[ -z "${local_ref:-}" || -z "${local_oid:-}" || -z "${remote_ref:-}" || -z "${remote_oid:-}" || -n "${extra:-}" ]]; then
    refusal 'malformed pre-push update'
  fi
  [[ "$local_oid" =~ ^[[:xdigit:]]+$ && "$remote_oid" =~ ^[[:xdigit:]]+$ && ${#local_oid} -eq ${#zero_oid} && ${#remote_oid} -eq ${#zero_oid} ]] || refusal 'malformed object ID'
  if [[ "$local_oid" == "$zero_oid" ]]; then
    # Deletions retain an exact empty policy universe. Full verification still
    # runs, while mutation receives its separate exact-empty range evidence.
    [[ "$remote_oid" == "$zero_oid" ]] || ranges+=(--range "$remote_oid" "$remote_oid")
    continue
  fi
  if [[ "$remote_oid" == "$zero_oid" ]]; then
    # Mutation keeps its conservative new-ref evidence independently of policy.
    ranges+=(--range invalid-base "$local_oid")
  else
    ranges+=(--range "$remote_oid" "$local_oid")
  fi
  if peel_commit_target "$local_ref" "$local_oid"; then
    if [[ "$remote_oid" == "$zero_oid" ]]; then
      resolve_integration_tip
      policy_base="$integration_tip"
    else
      git rev-parse --verify "$remote_oid^{commit}" >/dev/null 2>&1 || refusal "$remote_ref names unresolvable commit $remote_oid"
      policy_base="$remote_oid"
    fi
    add_policy_target "$policy_base..$peeled_object"
  fi
done

if [[ ${policy_targets[0]+present} ]]; then
  ./awf check commit-policy "${policy_targets[@]}"
fi
npm run check
