#!/usr/bin/env bash
# GENERATED by awf: do not edit; change .awf/ and run `awf render`
# Pre-commit payload: the configured aggregate check, then the project gate. Inert until wired into a hook setup you own, e.g. a
# .git/hooks/pre-commit stub containing:
#   exec bash .awf/hooks/pre-commit.sh "$@"
set -euo pipefail
./awf check
./awf check
