#!/usr/bin/env bash
# GENERATED by awf: do not edit; change .awf/ and run `awf render`
# Pre-merge-commit payload: the staged rendered-output check and
# current-state transition backstop on a merge git resolves by itself. Git runs no pre-commit
# hook for a true merge commit. A conflict-free automerge that lands two
# records on one identity, or a transition nobody authored, would otherwise reach the integration
# branch unchecked. Final message trailers and MERGE_HEAD parents are not available at this hook;
# commit-msg owns definitive stale-ADR authorization. Inert until
# wired into a hook setup you own, e.g. a
# .git/hooks/pre-merge-commit stub containing:
#   exec bash .awf/hooks/pre-merge-commit.sh "$@"
set -euo pipefail
./awf check staged
