#!/usr/bin/env bash
# GENERATED by awf: do not edit; change .awf/ and run `awf render`
# Pre-push payload: validates every pushed target against the optional commit
# policy before running the fullest configured gate. Inert until wired into a
# hook setup you own. A stub resolves the invoking worktree before delegating:
#   repo_root=$(git rev-parse --show-toplevel) || exit 1
#   exec bash "$repo_root/.awf/hooks/pre-push.sh" "$@"
set -euo pipefail

root="$(git rev-parse --show-toplevel)"
cd "$root"
empty_oid="$(git hash-object -t blob --stdin </dev/null)"
zero_oid="${empty_oid//?/0}"
mapfile -t updates
targets=()
declare -A seen_targets=()

refusal() {
  printf 'commit policy refused: %s\n' "$1" >&2
  printf '%s\n' 'nothing was pushed; reconcile the local object and commit policy, then retry the complete push' >&2
  exit 1
}

add_target() {
  [[ ${seen_targets[$1]+x} ]] && return
  seen_targets[$1]=1
  targets+=("$1")
}

add_object_target() {
  local source="$1"
  local object="$2"
  local type
  type="$(git cat-file -t "$object" 2>/dev/null)" || refusal "$source names missing object $object"
  if [[ "$type" == tag ]]; then
    object="$(git rev-parse --verify "$object^{}" 2>/dev/null)" || refusal "$source cannot be peeled"
    type="$(git cat-file -t "$object" 2>/dev/null)" || refusal "$source peels to missing object $object"
  fi
  if [[ "$type" == commit ]]; then
    add_target "$object"
    return
  fi
  printf 'commit policy note: %s resolves to non-commit %s %s; no commit added\n' "$source" "$type" "$object" >&2
}

for update in "${updates[@]}"; do
  IFS=' ' read -r local_ref local_oid remote_ref remote_oid extra <<< "$update"
  if [[ -z "${local_ref:-}" || -z "${local_oid:-}" || -z "${remote_ref:-}" || -z "${remote_oid:-}" || -n "${extra:-}" ]]; then
    refusal 'malformed pre-push update'
  fi
  [[ "$local_oid" =~ ^[[:xdigit:]]+$ && "$remote_oid" =~ ^[[:xdigit:]]+$ && ${#local_oid} -eq ${#zero_oid} && ${#remote_oid} -eq ${#zero_oid} ]] || refusal 'malformed object ID'
  [[ "$local_oid" == "$zero_oid" ]] && continue
  add_object_target "$local_ref" "$local_oid"
done

if ((${#targets[@]})); then
  ./awf check commit-policy "${targets[@]}"
fi
./awf check
