#!/usr/bin/env bash
# GENERATED by awf: do not edit; change .awf/ and run `awf render`
# Reference-transaction payload: validates the complete prepared local-branch
# update transaction against the optional commit policy. Inert until wired into
# a hook setup you own. A stub resolves the invoking worktree before delegating:
#   repo_root=$(git rev-parse --show-toplevel) || exit 1
#   exec bash "$repo_root/.awf/hooks/reference-transaction.sh" "$@"
set -euo pipefail

[[ "${1:-}" == "prepared" ]] || exit 0

root="$(git rev-parse --show-toplevel)"
cd "$root"
empty_oid="$(git hash-object -t blob --stdin </dev/null)"
zero_oid="${empty_oid//?/0}"
mapfile -t updates
targets=()
declare -A seen_targets=()

add_target() {
  [[ ${seen_targets[$1]+x} ]] && return
  seen_targets[$1]=1
  targets+=("$1")
}

valid_oid_or_symref() {
  [[ "$1" =~ ^[[:xdigit:]]+$ && ${#1} -eq ${#zero_oid} ]] && return
  [[ "$1" == ref:* ]] && git check-ref-format "${1#ref:}" >/dev/null 2>&1
}

valid_hook_ref() {
  if [[ "$1" == refs/* ]]; then
    git check-ref-format "$1" >/dev/null 2>&1
    return
  fi
  [[ "$1" =~ ^[A-Z][A-Z0-9_]*$ ]]
}

refusal() {
  printf '%s\n' "commit policy refused: $1" >&2
  printf '%s\n' 'refs changed: false' >&2
  printf '%s\n' 'policy verifier changed index: false' >&2
  printf '%s\n' 'index/worktree may already have changed before this hook; inspect git status' >&2
  printf '%s\n' 'reconcile the update records and commit policy, restore any unintended index/worktree change, then retry the complete transaction' >&2
  exit 1
}

for update in "${updates[@]}"; do
  IFS=' ' read -r old_oid new_oid ref extra <<< "$update"
  [[ -n "${old_oid:-}" && -n "${new_oid:-}" && -n "${ref:-}" && -z "${extra:-}" ]] || refusal "malformed reference-transaction update"
  valid_oid_or_symref "$old_oid" && valid_oid_or_symref "$new_oid" || refusal "malformed object ID"
  valid_hook_ref "$ref" || refusal "malformed reference name"
  [[ "$ref" == refs/heads/* ]] || continue
  [[ "$old_oid" != ref:* && "$new_oid" != ref:* ]] || refusal "branch update uses a symbolic target"
  [[ "$new_oid" == "$zero_oid" ]] && continue
  git rev-parse --verify "$new_oid^{commit}" >/dev/null 2>&1 || refusal "new branch target is not a resolvable commit"
  if [[ "$old_oid" == "$zero_oid" ]]; then
    add_target "$new_oid"
    continue
  fi
  git rev-parse --verify "$old_oid^{commit}" >/dev/null 2>&1 || refusal "old branch target is not a resolvable commit"
  if git merge-base --is-ancestor "$new_oid" "$old_oid"; then
    continue
  fi
  add_target "$old_oid..$new_oid"
done

if ((${#targets[@]})); then
  ./awf check commit-policy "${targets[@]}"
fi
