// GENERATED by awf: do not edit; change .awf/ and run `awf render`
// @ts-nocheck
import { randomUUID } from "node:crypto";
import { lstat, mkdir, readFile, realpath, rename, unlink, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  CONFIG_DIR_NAME,
  getAgentDir,
  parseFrontmatter,
  type ExtensionAPI,
} from "@earendil-works/pi-coding-agent";
import { StringEnum } from "@earendil-works/pi-ai";
import { Type } from "typebox";


import type { ConcreteModel, ExecutionOutcome, ProfileCapability, ProfileDefinition, ProfileRegistrationResult } from "pi-tools/subagent-profile";
import {
  GLOBAL_PREFERENCES_FILE,
  LOCAL_PREFERENCES_FILE,
  MODEL_REFERENCE_SCHEMA,
  PREFERENCE_FIELDS,
  PREFERENCE_ROLES,
  PREFERENCE_TIERS,
  PREFERENCES_BLOCKED,
  PREFERENCES_REPAIR,
  RECOMMENDED_PRESET,
  buildRoutingCard,
  loadPreferenceState,
  effectivePreferenceState,
  invalidText,
  registryFailures,
  resolveChildModel,
  routingPreview,
  type EffectivePreferenceState,
  type PreferenceField,
  type PreferenceSourceState,
  type SubagentModelPreferences,
} from "./model-routing.ts";

export const EXPLORE_TOOLS = ["read", "grep", "find", "ls", "bash"] as const;
export const GROUNDING_TOOLS = EXPLORE_TOOLS;
export const REVIEW_TOOLS = ["read", "grep", "find", "ls", "bash"] as const;
export const IMPLEMENT_TOOLS = ["read", "bash", "edit", "write", "grep", "find", "ls"] as const;
export const REVIEWER_PATHS = {
  adr: ".pi/agents/adr-reviewer.md",
  plan: ".pi/agents/plan-reviewer.md",
  code: ".pi/agents/code-reviewer.md",
} as const;
export const IMPLEMENTER_PATH = ".pi/agents/implementer.md";
export const EXPLORER_PATH = ".pi/agents/explorer.md";
export const GROUNDING_CHECKER_PATH = ".pi/agents/grounding-checker.md";

const preferenceNotices = new WeakSet<object>();
const SUBAGENT_TOOL_NAMES = new Set(["subagent_grounding", "subagent_explore", "subagent_review", "subagent_implement"]);
export const MAX_EXPLORATION_CONCURRENCY = 10;
type ReviewKind = keyof typeof REVIEWER_PATHS;
interface GitSnapshot { available: boolean; head?: string; status?: string; }
export interface ExtensionDependencies {
  readFile(path: string, encoding: "utf8"): Promise<string>;
  extensionFile: string;
  agentDir: string;
  configDirName: string;
  writeFile(path: string, data: string, options: { mode: number }): Promise<void>;
  mkdir(path: string, options: { recursive: true }): Promise<unknown>;
  rename(from: string, to: string): Promise<void>;
  unlink(path: string): Promise<void>;
  realpath(path: string): Promise<string>;
  lstat(path: string): Promise<{ isFile(): boolean; isSymbolicLink(): boolean }>;
}
function projectRoot(extensionFile: string): string { return resolve(dirname(extensionFile), "../../.."); }
function errorText(error: unknown): string { return error instanceof Error ? error.message : String(error); }
function errorCode(error: unknown): string | undefined { return typeof error === "object" && error !== null ? (error as { code?: string }).code : undefined; }

// A dispatched role's contract is a rendered agent artifact rather than a literal
// string here, so the durable prose is reviewable and drift-checked. Three
// behaviours are shared by every role that loads one: the missing-file error
// carries an actionable repair, the frontmatter is stripped rather than passed to
// the child, and an empty instruction body is a hard error instead of a silently
// contentless prompt. What varies per role is only the wording, so each caller
// supplies its own noun, repair clause, and prepend.
interface ContractSource {
  relative: string;
  noun: string;
  repair: string;
  prepend: string;
}

async function loadAgentContract(deps: ExtensionDependencies, root: string, source: ContractSource): Promise<string> {
  let content: string;
  try { content = await deps.readFile(join(root, source.relative), "utf8"); }
  catch {
    throw new Error(`Missing Pi ${source.noun} ${source.relative}. ${source.repair}`);
  }
  const parsed = parseFrontmatter<Record<string, unknown>>(content);
  if (!parsed.body.trim()) throw new Error(`Pi ${source.noun} ${source.relative} has no instruction body; run ./awf render.`);
  return `${source.prepend}\n\n${parsed.body}`;
}

function stripTerminalLineEnding(value: string): string {
  if (value.endsWith("\r\n")) return value.slice(0, -2);
  if (value.endsWith("\n")) return value.slice(0, -1);
  return value;
}

async function snapshot(pi: ExtensionAPI, cwd: string): Promise<GitSnapshot> {
  const head = await pi.exec("git", ["rev-parse", "HEAD"], { cwd });
  if (head.code !== 0) return { available: false };
  const status = await pi.exec("git", ["status", "--short"], { cwd });
  return { available: status.code === 0, head: head.stdout.trim(), status: status.stdout };
}

async function canonicalPath(deps: ExtensionDependencies, path: string, failureMessage: string): Promise<string> {
  try { return await deps.realpath(path); }
  catch (error) { throw new Error(`${failureMessage}: ${errorText(error)}`, { cause: error }); }
}

async function resolveVerificationCheckout(
  pi: ExtensionAPI, deps: ExtensionDependencies, root: string, requested: string | undefined,
): Promise<string> {
  if (requested === undefined) return root;
  const normalized = requested.startsWith("@") ? requested.slice(1) : requested;
  if (normalized === "") throw new Error("verificationCheckout is empty after removing one leading @; omit the field for root verification or provide a registered checkout root.");
  const candidate = resolve(root, normalized);
  const checkout = await canonicalPath(deps, candidate, `verificationCheckout does not exist: ${candidate}`);
  const canonicalRoot = await canonicalPath(deps, root, "Cannot resolve the project root checkout.");
  const selectedGitEntry = join(checkout, ".git");
  let entry: { isFile(): boolean; isSymbolicLink(): boolean } | undefined;
  try { entry = await deps.lstat(selectedGitEntry); }
  catch (error) {
    if (errorCode(error) !== "ENOENT") throw new Error(`Cannot inspect verificationCheckout .git entry ${selectedGitEntry}: ${errorText(error)}`, { cause: error });
  }
  if (entry?.isSymbolicLink()) throw new Error(`verificationCheckout .git entry must not be a symlink: ${selectedGitEntry}`);

  const top = await pi.exec("git", ["rev-parse", "--show-toplevel"], { cwd: checkout });
  if (top.code !== 0) throw new Error(`verificationCheckout must be a live registered checkout root for this repository: ${checkout}`);
  const topPath = stripTerminalLineEnding(top.stdout);
  const canonicalTop = await canonicalPath(deps, topPath, `verificationCheckout Git root does not exist: ${topPath}`);
  if (canonicalTop !== checkout) throw new Error(`verificationCheckout must name the checkout root, not a subdirectory: ${checkout}`);
  const rootCommon = await pi.exec("git", ["rev-parse", "--path-format=absolute", "--git-common-dir"], { cwd: root });
  const checkoutCommon = await pi.exec("git", ["rev-parse", "--path-format=absolute", "--git-common-dir"], { cwd: checkout });
  if (rootCommon.code !== 0 || checkoutCommon.code !== 0) throw new Error(`verificationCheckout must be a live registered checkout root for this repository: ${checkout}`);
  const canonicalRootCommon = await canonicalPath(deps, stripTerminalLineEnding(rootCommon.stdout), "Cannot resolve the project root Git common directory.");
  const canonicalCheckoutCommon = await canonicalPath(deps, stripTerminalLineEnding(checkoutCommon.stdout), `Cannot resolve verificationCheckout Git common directory: ${checkout}`);
  if (canonicalRootCommon !== canonicalCheckoutCommon) throw new Error(`verificationCheckout must belong to the same repository as the project root: ${checkout}`);

  const gitDirectory = await pi.exec("git", ["rev-parse", "--absolute-git-dir"], { cwd: checkout });
  if (gitDirectory.code !== 0) throw new Error(`Cannot resolve verificationCheckout absolute Git directory: ${checkout}`);
  const canonicalGitDirectory = await canonicalPath(deps, stripTerminalLineEnding(gitDirectory.stdout), `Cannot resolve verificationCheckout absolute Git directory: ${checkout}`);
  if (canonicalGitDirectory === canonicalCheckoutCommon) {
    if (checkout !== canonicalRoot) throw new Error(`verificationCheckout must identify the project root or a live linked checkout, not a copied primary Git pointer: ${checkout}`);
    return checkout;
  }
  let backlink: string;
  try { backlink = await deps.readFile(join(canonicalGitDirectory, "gitdir"), "utf8"); }
  catch (error) {
    if (errorCode(error) === "ENOENT") throw new Error(`verificationCheckout must be a live linked checkout with an administrative backlink: ${checkout}`, { cause: error });
    throw new Error(`Cannot read verificationCheckout administrative backlink for ${checkout}: ${errorText(error)}`, { cause: error });
  }
  if (!entry?.isFile()) throw new Error(`verificationCheckout linked .git entry must be a non-symlink regular file: ${selectedGitEntry}`);
  const backlinkPath = stripTerminalLineEnding(backlink);
  if (backlinkPath === "") throw new Error(`verificationCheckout administrative backlink is empty: ${join(canonicalGitDirectory, "gitdir")}`);
  const canonicalBacklink = await canonicalPath(deps, resolve(canonicalGitDirectory, backlinkPath), `Cannot resolve verificationCheckout administrative backlink for ${checkout}`);
  if (canonicalBacklink !== selectedGitEntry) throw new Error(`verificationCheckout administrative backlink ${canonicalBacklink} does not identify the registered checkout ${checkout}`);
  return checkout;
}

const REGISTRATION_ID = "awf:subagent-profiles:v2";
const PROTOCOL_VERSION = 2;
const REQUEST_EVENT = "pi-tools:subagent-profiles:request";
const CAPABILITY_EVENT = "pi-tools:subagent-profiles:capability";
const RESULT_EVENT = "pi-tools:subagent-profiles:registration-result";
const MAX_GROUNDING_CONCURRENCY = 10;
const MAX_REVIEW_CONCURRENCY = 10;
type Role = "grounding" | "explore" | "review" | "implement";
type ResolutionSource = "requested" | "project-role" | "global-role" | "project-default" | "global-default" | "inherited";
interface InvocationRouting {
  requestedModel: string | null;
  resolvedProvider: string;
  resolvedModel: string;
  resolutionSource: ResolutionSource;
}
const RESOLUTION_SOURCE_SCHEMA = StringEnum(["requested", "project-role", "global-role", "project-default", "global-default", "inherited"] as const);
const ROUTING_PROFILE_DATA_FIELDS = {
  requestedModel: Type.Union([Type.String(), Type.Null()]),
  resolvedProvider: Type.String(),
  resolvedModel: Type.String(),
  resolutionSource: RESOLUTION_SOURCE_SCHEMA,
};
const GIT_SNAPSHOT_SCHEMA = Type.Union([
  Type.Object({ available: Type.Literal(false) }, { additionalProperties: false }),
  Type.Object({ available: Type.Literal(true), head: Type.String(), status: Type.String() }, { additionalProperties: false }),
]);
const COMMIT_VERIFICATION_SCHEMA = StringEnum(["verified", "unavailable"] as const);

/** Registers awf workflow policy through pi-tools; it never starts or renders a child itself. */
export function registerSubagentTools(pi: ExtensionAPI, deps: ExtensionDependencies): void {
  const root = projectRoot(deps.extensionFile);
  let session: { modelRegistry: any; model: any; ui: any; sessionManager: any } | undefined;
  let reportedReason: string | undefined;
  let notified = false;
  let registered = false;
  const report = (reason: string) => {
    if (reportedReason !== undefined && reportedReason !== reason) return;
    reportedReason ??= reason;
    if (!session || notified) return;
    notified = true;
    session.ui?.notify?.(`awf subagent tools require independently installed hypnotox/pi-tools with protocol v2 (${reason}). Install or update pi-tools and reload Pi; awf provides no fallback.`, "error");
  };
  const reloadState = async (): Promise<EffectivePreferenceState> => {
    if (!session) throw new Error("Subagent profiles are unavailable until Pi session_start captures the live model registry.");
    return loadPreferenceState(deps, session.modelRegistry);
  };
  const notifyPreferenceState = (state: EffectivePreferenceState): void => {
    const identity = session?.sessionManager;
    if (!identity || typeof identity !== "object" || preferenceNotices.has(identity)) return;
    if (state.blocked) session!.ui.notify(`${PREFERENCES_BLOCKED} ${state.errors.join("; ")}. ${PREFERENCES_REPAIR}`, "error");
    else if (state.missing.length > 0) session!.ui.notify(`Subagent model preferences are incomplete; missing: ${state.missing.join(", ")}. Run /awf-subagent-models to configure roles and tiers.`, "info");
    else return;
    preferenceNotices.add(identity);
  };
  const invocationRouting = new WeakMap<object, InvocationRouting>();
  const selectModel = async (context: any, role: Role): Promise<ConcreteModel> => {
    const state = await reloadState();
    notifyPreferenceState(state);
    // pi-tools validates this concrete selection against its ProfileContext registry again.
    const selected = resolveChildModel(session!.modelRegistry, context.parent?.model ?? session!.model, role, context.args.model, state);
    invocationRouting.set(context, {
      requestedModel: selected.requested ?? null,
      resolvedProvider: selected.model.provider,
      resolvedModel: selected.model.id,
      resolutionSource: selected.source,
    });
    return { provider: selected.model.provider, id: selected.model.id, thinkingLevels: ["off", "minimal", "low", "medium", "high", "xhigh", "max"] };
  };
  const routingFor = (context: object): InvocationRouting => {
    const routing = invocationRouting.get(context);
    if (!routing) throw new Error("pi-tools profile lifecycle called beforeRun without completing selectModel for the same invocation context.");
    return routing;
  };
  pi.on("before_agent_start", async (event: any) => {
    const selected = Array.isArray(event.systemPromptOptions?.selectedTools) ? event.systemPromptOptions.selectedTools : pi.getActiveTools?.();
    if (!Array.isArray(selected) || !selected.some((tool: string) => SUBAGENT_TOOL_NAMES.has(tool))) return undefined;
    const state = await reloadState(); notifyPreferenceState(state);
    const card = buildRoutingCard(state);
    return { systemPrompt: event.systemPrompt + "\n\n" + card };
  });
function modelLabel(model: any, _parent?: any, _configured?: any, _recommended?: any) { return `${model.provider}/${model.id} - ${model.name}`; }

const SLOT_GUIDANCE: Array<{ key: PreferenceField; guidance: string }> = [
  { key: "default", guidance: "Shared fallback for every role; a mid-tier coding model fits." },
  { key: "grounding", guidance: "Grounding verifies designs against source; favor the strongest model." },
  { key: "exploration", guidance: "Exploration fans out cheap reads; favor the cheapest capable model." },
  { key: "review", guidance: "Review judges finished work; favor the strongest model." },
  { key: "implementation", guidance: "Implementation edits code; a mid-tier coding model fits." },
  { key: "small", guidance: "Small is for narrow, mechanical, low-ambiguity work." },
  { key: "standard", guidance: "Standard is for substantive but bounded work." },
  { key: "large", guidance: "Large is for broad, intricate, cross-cutting, or high-consequence work." },
];

  pi.registerCommand("awf-subagent-models", {
    description: "Configure per-role subagent model preferences.",
    handler: async (_args: string, ctx: any) => {
      if (ctx.mode !== "tui" || typeof ctx.ui?.select !== "function") {
        ctx.ui?.notify?.("awf-subagent-models requires an interactive TUI session.", "error");
        return;
      }
      const state = await reloadState();
      const canceled = () => ctx.ui.notify("Subagent model preferences unchanged.", "info");
      const globalLabel = `User-global (${state.global.path})`;
      const scopeChoice = await ctx.ui.select("Preference scope", [globalLabel, `Project-local (${state.project.path})`]);
      if (scopeChoice === undefined) return canceled();
      const scope = scopeChoice === globalLabel ? state.global : state.project;
      let snapshot: string | undefined;
      try { snapshot = await deps.readFile(scope.path, "utf8"); }
      catch (error) {
        if (errorCode(error) !== "ENOENT") { ctx.ui.notify(`Cannot read ${scope.path}: ${errorText(error)}`, "error"); return; }
        snapshot = undefined;
      }
      const scopeInvalid = state.invalid.filter((item) => item.scope === scope.scope);
      const currentLines = scopeInvalid.length > 0 ? scopeInvalid.map(invalidText) : Object.entries(scope.values).map(([key, value]) => `${key}: ${value}`);
      const proceed = await ctx.ui.confirm(
        "Current subagent model preferences",
        `${scope.path}\n${currentLines.join("\n") || "(empty)"}\n\nEffective routing now:\n${routingPreview(state.project, state.global, state).join("\n")}\n\nThis wizard configures child routing only; the parent session remains the mastermind for brainstorming and plan authoring. Configure this scope now?`,
      );
      if (!proceed) return canceled();
      const presetIssues: string[] = [];
      for (const [slot, reference] of Object.entries(RECOMMENDED_PRESET)) {
        const slash = reference.indexOf("/");
        const found = ctx.modelRegistry.find(reference.slice(0, slash), reference.slice(slash + 1));
        if (!found) presetIssues.push(`preset ${slot} model is unregistered.`);
        else if (!ctx.modelRegistry.hasConfiguredAuth(found)) presetIssues.push(`preset ${slot} model is unauthenticated.`);
      }
      let next: SubagentModelPreferences | undefined;
      if (presetIssues.length === 0) {
        const preset = "Apply recommended GPT-5.6 preset";
        const mode = await ctx.ui.select("Configuration mode", [preset, "Configure each slot"]);
        if (mode === undefined) return canceled();
        if (mode === preset) next = { ...RECOMMENDED_PRESET };
      } else {
        ctx.ui.notify(`Recommended preset unavailable: ${presetIssues.join(" ")}`, "info");
      }
      if (next === undefined) {
        const chosen: SubagentModelPreferences = {};
        const unset = "leave unset (use fallback chain)";
        for (const slot of SLOT_GUIDANCE) {
          const options = [unset, ...ctx.modelRegistry.getAll().map((model: any) => modelLabel(model, ctx.model, scope.values[slot.key], RECOMMENDED_PRESET[slot.key]))];
          const picked = await ctx.ui.select(`${slot.key}: ${slot.guidance}`, options);
          if (picked === undefined) return canceled();
          if (picked !== unset) (chosen as Record<string, string>)[slot.key] = picked.split(" ")[0];
        }
        next = chosen;
      }
      const content = `${JSON.stringify(next, null, 2)}\n`;
      const nextScope: PreferenceSourceState = { ...scope, values: next, invalid: [] };
      const previewGlobal = scope.scope === "global" ? nextScope : state.global;
      const previewProject = scope.scope === "project" ? nextScope : state.project;
      const previewState = effectivePreferenceState(previewGlobal, previewProject, registryFailures(ctx.modelRegistry, [previewGlobal, previewProject]));
      const preview = routingPreview(previewProject, previewGlobal, previewState);
      const confirmed = await ctx.ui.confirm("Save subagent model preferences", `${scope.path}\n${content}\nEffective routing after save:\n${preview.join("\n")}\n\nWrite this file?`);
      if (!confirmed) return canceled();
      if (scope.scope === "project") {
        const workTree = await pi.exec("git", ["rev-parse", "--is-inside-work-tree"], { cwd: root });
        if (workTree.code !== 0) {
          ctx.ui.notify("Not a git work tree; skipping ignore check.", "info");
        } else {
          const relative = `${deps.configDirName}/${LOCAL_PREFERENCES_FILE}`;
          const ignored = await pi.exec("git", ["check-ignore", "-q", relative], { cwd: root });
          if (ignored.code !== 0) {
            const append = await ctx.ui.confirm("Gitignore rule required", `${relative} is not ignored. Append the rule to the project root .gitignore?`);
            if (!append) { ctx.ui.notify("Save canceled: the project-local preference file must be gitignored.", "error"); return; }
            const gitignorePath = join(root, ".gitignore");
            let existing = "";
            try { existing = await deps.readFile(gitignorePath, "utf8"); }
            catch (error) {
              if (errorCode(error) !== "ENOENT") { ctx.ui.notify(`Cannot read ${gitignorePath}: ${errorText(error)}`, "error"); return; }
            }
            const separator = existing === "" || existing.endsWith("\n") ? "" : "\n";
            try { await deps.writeFile(gitignorePath, `${existing}${separator}${relative}\n`, { mode: 0o644 }); }
            catch (error) { ctx.ui.notify(`Cannot update ${gitignorePath}: ${errorText(error)}`, "error"); return; }
          }
        }
      }
      try { await deps.mkdir(dirname(scope.path), { recursive: true }); }
      catch (error) { ctx.ui.notify(`Cannot create ${dirname(scope.path)}: ${errorText(error)}`, "error"); return; }
      let latest: string | undefined;
      try { latest = await deps.readFile(scope.path, "utf8"); }
      catch (error) {
        if (errorCode(error) !== "ENOENT") { ctx.ui.notify(`Cannot re-read ${scope.path}: ${errorText(error)}`, "error"); return; }
        latest = undefined;
      }
      if (latest !== snapshot) {
        ctx.ui.notify(`Save canceled: ${scope.path} was modified concurrently; rerun /awf-subagent-models.`, "error");
        return;
      }
      const temp = `${scope.path}.${randomUUID()}.tmp`;
      try {
        await deps.writeFile(temp, content, { mode: 0o600 });
        await deps.rename(temp, scope.path);
      } catch (error) {
        try { await deps.unlink(temp); } catch { /* best-effort temp cleanup */ }
        ctx.ui.notify(`Save failed: ${errorText(error)}`, "error");
        return;
      }
      const saved = await reloadState();
      if (saved.blocked) {
        ctx.ui.notify(`Preferences saved, but they are invalid and block implicit routing: ${saved.errors.join(" ")} ${PREFERENCES_REPAIR}`, "error");
        return;
      }
      ctx.ui.notify("Subagent model preferences saved.", "info");
    },
  });
  const prepare = async (context: any, tools: readonly string[], source: ContractSource) => ({
    cwd: root, prompt: context.args.task, toolPolicy: { mode: "allowlist" as const, tools: [...tools] },
    systemPrompt: await loadAgentContract(deps, root, source),
  });
  const profiles: ProfileDefinition[] = [
    { id: "awf-grounding", toolName: "subagent_grounding", label: "Grounding Subagent", description: "Run one fresh-context, no-mutation grounding check. Omit model for configured or inherited routing; use an exact tier provider/model-id only for deliberate override. Omission is the only default form.", promptSnippet: "Ground an agreed design against source and project constraints", promptGuidelines: ["Use subagent_grounding whenever the rendered grounding support contract calls for repository-premise checks; include the complete grounding brief in task. Omit model for configured or inherited routing; use the selected tier's exact provider/model-id only for deliberate override. Omit the model field to use configured or inherited routing."], parameters: Type.Object({ task: Type.String({ minLength: 1 }), model: Type.Optional(MODEL_REFERENCE_SCHEMA) }, { additionalProperties: false }), profileDataSchema: Type.Object({ ...ROUTING_PROFILE_DATA_FIELDS }, { additionalProperties: false }), concurrency: MAX_GROUNDING_CONCURRENCY, selectModel: (c: any) => selectModel(c, "grounding"), beforeRun: (c: any) => routingFor(c), prepare: (c: any) => prepare(c, GROUNDING_TOOLS, { relative: GROUNDING_CHECKER_PATH, repair: "Enable the grounding-checker agent and run ./awf render.", noun: "grounding-checker", prepend: "You are the governed grounding-check subagent. You are report-only: never edit or commit." }), afterRun: (_o: any, state: any) => ({ profileData: state }) },
    { id: "awf-explore", toolName: "subagent_explore", label: "Explore Subagent", description: "Run one fresh-context, no-mutation exploration child. Omit model for configured or inherited routing; use an exact tier provider/model-id only for deliberate override. Omission is the only default form.", promptSnippet: "Delegate a self-contained read-oriented investigation to fresh context", promptGuidelines: ["Use subagent_explore for one scoped investigation; include all required context in task. Omit model for configured or inherited routing; use the selected tier's exact provider/model-id only for deliberate override. Omit the model field to use configured or inherited routing."], parameters: Type.Object({ task: Type.String({ minLength: 1 }), breadth: StringEnum(["targeted", "bounded", "broad"] as const), detail: StringEnum(["paths", "summary", "analysis"] as const), model: Type.Optional(MODEL_REFERENCE_SCHEMA) }, { additionalProperties: false }), profileDataSchema: Type.Object({ ...ROUTING_PROFILE_DATA_FIELDS, breadth: StringEnum(["targeted", "bounded", "broad"] as const), detail: StringEnum(["paths", "summary", "analysis"] as const) }, { additionalProperties: false }), concurrency: MAX_EXPLORATION_CONCURRENCY, selectModel: (c: any) => selectModel(c, "explore"), beforeRun: (c: any) => ({ ...routingFor(c), breadth: c.args.breadth, detail: c.args.detail }), prepare: (c: any) => prepare(c, EXPLORE_TOOLS, { relative: EXPLORER_PATH, repair: "Enable the explorer agent and run ./awf render.", noun: "explorer", prepend: `You are the governed exploration subagent. You are report-only: never edit or commit.\nSelected breadth maximum: ${c.args.breadth}\nSelected report detail: ${c.args.detail}` }), afterRun: (_o: any, state: any) => ({ profileData: state }) },
    { id: "awf-review", toolName: "subagent_review", label: "Review Subagent", description: "Run one governed report-only ADR, plan, or code reviewer in fresh context. Omit model for configured or inherited routing; use an exact tier provider/model-id only for deliberate override. Omission is the only default form.", promptSnippet: "Delegate governed ADR, plan, or code review to fresh context", promptGuidelines: ["Use subagent_review with kind adr, plan, or code and a self-contained review brief. Omit model for configured or inherited routing; use the selected tier's exact provider/model-id only for deliberate override. Omit the model field to use configured or inherited routing."], parameters: Type.Object({ kind: StringEnum(["adr", "plan", "code"] as const), task: Type.String({ minLength: 1 }), model: Type.Optional(MODEL_REFERENCE_SCHEMA) }, { additionalProperties: false }), profileDataSchema: Type.Object({ ...ROUTING_PROFILE_DATA_FIELDS, kind: StringEnum(["adr", "plan", "code"] as const) }, { additionalProperties: false }), concurrency: MAX_REVIEW_CONCURRENCY, selectModel: (c: any) => selectModel(c, "review"), beforeRun: (c: any) => ({ ...routingFor(c), kind: c.args.kind }), prepare: (c: any) => prepare(c, REVIEW_TOOLS, { relative: REVIEWER_PATHS[c.args.kind as ReviewKind], repair: `Enable the matching ${c.args.kind}-reviewer agent and run ./awf render.`, noun: "reviewer", prepend: `You are the governed ${c.args.kind} reviewer. You are report-only: never edit or commit.` }), afterRun: (_o: any, state: any) => ({ profileData: state }) },
    { id: "awf-implement", toolName: "subagent_implement", label: "Implementation Subagent", description: "Run one serialized implementation child while verifying commit policy in the caller-selected project checkout. Call this tool alone in its parent tool batch. Omit verificationCheckout for the project root. Omit model for configured or inherited routing; use an exact tier provider/model-id only for deliberate override. Omission is the only model default form.", promptSnippet: "Delegate one sequential implementation task to fresh context", promptGuidelines: ["Call subagent_implement alone in a tool batch, never in parallel; set allowCommits explicitly. Set verificationCheckout when implementation intentionally targets a managed worktree; this changes verification identity only, not parent or child CWD. Omit it for root work. Omit model for configured or inherited routing; use the selected tier's exact provider/model-id only for deliberate override. Omit the model field to use configured or inherited routing."], parameters: Type.Object({ task: Type.String({ minLength: 1 }), allowCommits: Type.Boolean(), verificationCheckout: Type.Optional(Type.String()), model: Type.Optional(MODEL_REFERENCE_SCHEMA) }, { additionalProperties: false }), profileDataSchema: Type.Object({ ...ROUTING_PROFILE_DATA_FIELDS, allowCommits: Type.Boolean(), verificationCheckout: Type.String(), before: GIT_SNAPSHOT_SCHEMA, after: GIT_SNAPSHOT_SCHEMA, commitVerification: COMMIT_VERIFICATION_SCHEMA }, { additionalProperties: false }), concurrency: 1, exclusiveParentBatch: true, selectModel: (c: any) => selectModel(c, "implement"), beforeRun: async (c: any) => {
      const verificationCheckout = await resolveVerificationCheckout(pi, deps, root, c.args.verificationCheckout);
      return { ...routingFor(c), allowCommits: c.args.allowCommits, verificationCheckout, before: await snapshot(pi, verificationCheckout) };
    }, prepare: (c: any) => prepare(c, IMPLEMENT_TOOLS, { relative: IMPLEMENTER_PATH, repair: "Enable the implementer agent and run ./awf render.", noun: "implementer", prepend: `You are the governed implementation subagent. ${c.args.allowCommits ? "Commits are allowed when the task requests them; you are the phase owner." : "Commits are forbidden; do not change HEAD. You are a helper."}` }), afterRun: async (_outcome: ExecutionOutcome, state: any) => { const after = await snapshot(pi, state.verificationCheckout); const verified = state.before.available && after.available; const changed = verified && state.before.head !== after.head; const failure = !state.allowCommits && changed ? `Implementation committed despite allowCommits=false (HEAD ${state.before.head} -> ${after.head}) in verification checkout ${state.verificationCheckout}; changes were not reverted.` : state.allowCommits && verified && !changed ? `Implementation was commit-capable but created no commit in ${state.verificationCheckout} (HEAD unchanged at ${state.before.head}). If work occurred in another registered worktree, retry with verificationCheckout set to that checkout root. A stopped report must carry the working-tree status, work completed, work remaining, the named failing check with its actual output, and what was already tried.` : undefined; return { ...(failure ? { failure } : {}), profileData: { ...state, after, commitVerification: verified ? "verified" : "unavailable" } }; } },
  ];
  const register = (capability: ProfileCapability) => {
    if (capability.correlationId !== undefined && capability.correlationId !== correlationId) return;
    if (capability.protocolVersion !== PROTOCOL_VERSION || typeof capability.register !== "function") return report("incompatible capability");
    const receipt = capability.register({ registrationId: REGISTRATION_ID, profiles, suppressDefault: true });
    if (receipt.state === "registered") registered = true;
    if (receipt.state === "rejected" || receipt.state === "late") report(receipt.reason ?? receipt.state);
  };
  pi.events?.on?.(CAPABILITY_EVENT, (capability: any) => register(capability as ProfileCapability));
  pi.events?.on?.(RESULT_EVENT, (result: any) => { result = result as ProfileRegistrationResult; if (result.registrationId !== REGISTRATION_ID) return; if (result.protocolVersion !== PROTOCOL_VERSION || result.state !== "registered") report(result.reason ?? "registration rejected"); else registered = true; });
  const correlationId = randomUUID();
  pi.events?.emit?.(REQUEST_EVENT, { protocolVersion: PROTOCOL_VERSION, correlationId });
  pi.on("session_start", (_event: any, ctx: any) => { session = { modelRegistry: ctx.modelRegistry, model: ctx.model, ui: ctx.ui, sessionManager: ctx.sessionManager }; setTimeout(() => { if (reportedReason !== undefined) report(reportedReason); else if (!registered) report("missing, late, or incompatible capability"); }, 0); });
}

export default async function (pi: ExtensionAPI): Promise<void> {
  registerSubagentTools(pi, { readFile, extensionFile: fileURLToPath(import.meta.url), agentDir: getAgentDir(), configDirName: CONFIG_DIR_NAME, writeFile, mkdir, rename, unlink, realpath, lstat });
}
