// GENERATED by awf: do not edit; change .awf/ and run `awf render`
// @ts-nocheck
/* c8 ignore start */
import { randomUUID } from "node:crypto";
import { lstat, mkdir, readFile, realpath, rename, unlink, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  CONFIG_DIR_NAME,
  getAgentDir,
  getMarkdownTheme,
  getPackageDir,
  keyHint,
  parseFrontmatter,
  type ExtensionAPI,
} from "@earendil-works/pi-coding-agent";
import { StringEnum } from "@earendil-works/pi-ai";
import { Container, Markdown, Spacer, Text } from "@earendil-works/pi-tui";
import { Type } from "typebox";
import {
  createRunner,
  productionRunnerDependencies,
  truncateFailure,
  type DisplayEvent,
  type RunRequest,
  type Runner,
  type ThinkingLevel,
  type Usage,
} from "./runner.ts";
import {
  GLOBAL_PREFERENCES_FILE,
  LOCAL_PREFERENCES_FILE,
  MODEL_REFERENCE_SCHEMA,
  PREFERENCE_FIELDS,
  PREFERENCE_ROLES,
  PREFERENCE_TIERS,
  PREFERENCES_BLOCKED,
  PREFERENCES_REPAIR,
  RECOMMENDED_PRESET,
  ROUTING_CARD_OVERFLOW_WARNING,
  buildRoutingCard,
  loadPreferenceState,
  effectivePreferenceState,
  invalidText,
  parseExactModelReference,
  registryFailures,
  resolveChildModel,
  routingPreview,
  type EffectivePreferenceState,
  type ModelSource,
  type PreferenceField,
  type PreferenceSourceState,
  type SubagentModelPreferences,
} from "./model-routing.ts";

// Retained entrypoints use this floor. The optional using_effort companion also requires active-tool APIs and the package-exported real-path file-mutation queue; Remote events remain advisory publication only.
export const MIN_PI_VERSION = "0.81.1";
const MINIMUM_RUNTIME_NOTICE = Symbol.for("awf.pi.minimum-runtime-notified");
export interface MinimumRuntimeDependencies { packageVersion: string; }
export type MinimumRuntimeAPI = "on" | "eventsOn" | "eventsEmit" | "appendEntry" | "registerTool" | "registerCommand" | "queueCommand" | "exec" | "getThinkingLevel" | "getActiveTools" | "setActiveTools";
export type MinimumRuntimeExternalAPI = "withFileMutationQueue";
function parseVersion(value: string): [number, number, number] | undefined {
  const match = /^(\d+)\.(\d+)\.(\d+)(?:[-+].*)?$/.exec(value);
  return match ? [Number(match[1]), Number(match[2]), Number(match[3])] : undefined;
}
export function versionSupported(value: string): boolean {
  const actual = parseVersion(value);
  const minimum = parseVersion(MIN_PI_VERSION)!;
  if (!actual) return false;
  for (let i = 0; i < minimum.length; i++) {
    if (actual[i] !== minimum[i]) return actual[i] > minimum[i];
  }
  return true;
}
export function guardMinimumRuntime(pi: ExtensionAPI, deps: MinimumRuntimeDependencies, required: readonly MinimumRuntimeAPI[]): boolean {
  const requirements: Record<MinimumRuntimeAPI, boolean> = {
    on: typeof pi.on === "function", eventsOn: typeof pi.events?.on === "function", eventsEmit: typeof pi.events?.emit === "function",
    appendEntry: typeof pi.appendEntry === "function", registerTool: typeof pi.registerTool === "function", registerCommand: typeof pi.registerCommand === "function",
    queueCommand: typeof pi.queueCommand === "function", exec: typeof pi.exec === "function", getThinkingLevel: typeof pi.getThinkingLevel === "function", getActiveTools: typeof pi.getActiveTools === "function", setActiveTools: typeof (pi as any).setActiveTools === "function",
  };
  const missing = required.filter((name) => !requirements[name]);
  if (versionSupported(deps.packageVersion) && missing.length === 0) return true;
  if (typeof pi.on !== "function") return false;
  pi.on("session_start", async (_event, ctx) => {
    if ((globalThis as any)[MINIMUM_RUNTIME_NOTICE]) return;
    (globalThis as any)[MINIMUM_RUNTIME_NOTICE] = true;
    const missingAPI = missing.length > 0 ? ` Missing runtime APIs: ${missing.join(", ")}.` : "";
    ctx.ui.notify(`awf Pi extensions require Pi ${MIN_PI_VERSION} or newer with their factory event, persistence, tool, command, process, and thinking APIs; found ${deps.packageVersion}.${missingAPI} Upgrade Pi and reload.`, "error");
  });
  return false;
}
export const EXPLORE_TOOLS = ["read", "grep", "find", "ls", "bash"] as const;
export const GROUNDING_TOOLS = EXPLORE_TOOLS;
export const REVIEW_TOOLS = ["read", "grep", "find", "ls", "bash"] as const;
export const IMPLEMENT_TOOLS = ["read", "bash", "edit", "write", "grep", "find", "ls"] as const;
export const REVIEWER_PATHS = {
  adr: ".pi/agents/adr-reviewer.md",
  plan: ".pi/agents/plan-reviewer.md",
  code: ".pi/agents/code-reviewer.md",
} as const;
export const IMPLEMENTER_PATH = ".pi/agents/implementer.md";
export const EXPLORER_PATH = ".pi/agents/explorer.md";
export const GROUNDING_CHECKER_PATH = ".pi/agents/grounding-checker.md";

const preferenceNotices = new WeakSet<object>();
const SUBAGENT_TOOL_NAMES = new Set(["subagent_grounding", "subagent_explore", "subagent_review", "subagent_implement"]);
const COLLAPSED_EVENT_COUNT = 10;
export const MAX_EXPLORATION_CONCURRENCY = 10;
const MAX_TASK_PREVIEW_BYTES = 512;
const MAX_FALLBACK_BYTES = 2 * 1024;
const TASK_TRUNCATION = "[task truncated]";
const DISPLAY_TRUNCATION = "[display truncated]";
type ReviewKind = keyof typeof REVIEWER_PATHS;
interface GitSnapshot { available: boolean; head?: string; status?: string; }
export type SubagentState = "queued" | "running" | "completed" | "failed" | "aborted";
export interface ExecutionMetadata extends Record<string, unknown> {
  resolvedModel: string;
  requestedModel?: string;
  modelSource: ModelSource;
  thinkingLevel: ThinkingLevel;
  options: Readonly<Record<string, string | boolean>>;
}
export interface SubagentDetails extends ExecutionMetadata {
  role: RunRequest["role"];
  task: string;
  state: SubagentState;
  events: readonly DisplayEvent[];
  omittedEvents: number;
  stderr?: string;
  usage?: Usage;
  model?: string;
  modelChanged?: boolean;
  modelMismatch?: boolean;
  latestCacheHitRate?: number;
  stopReason?: string;
  awfFailure?: true;
  [roleSpecific: string]: unknown;
}
export interface ExtensionDependencies {
  readFile(path: string, encoding: "utf8"): Promise<string>;
  runner: Runner;
  packageVersion: string;
  extensionFile: string;
  agentDir: string;
  configDirName: string;
  writeFile(path: string, data: string, options: { mode: number }): Promise<void>;
  mkdir(path: string, options: { recursive: true }): Promise<unknown>;
  rename(from: string, to: string): Promise<void>;
  unlink(path: string): Promise<void>;
  realpath(path: string): Promise<string>;
  lstat(path: string): Promise<{ isFile(): boolean; isSymbolicLink(): boolean }>;
  now?: () => number;
  observationId?: () => string;
}
function utf8Bound(value: string, maximum: number, marker: string): string {
  if (Buffer.byteLength(value, "utf8") <= maximum) return value;
  let end = Math.min(value.length, maximum - Buffer.byteLength(marker, "utf8"));
  while (end > 0 && Buffer.byteLength(value.slice(0, end), "utf8") > maximum - Buffer.byteLength(marker, "utf8")) end--;
  return value.slice(0, Math.max(0, end)) + marker;
}
function projectRoot(extensionFile: string): string { return resolve(dirname(extensionFile), "../../.."); }
function errorText(error: unknown): string { return error instanceof Error ? error.message : String(error); }
function errorCode(error: unknown): string | undefined { return typeof error === "object" && error !== null ? (error as { code?: string }).code : undefined; }

export function createLimiter(limit: number) {
  let active = 0;
  const waiters: Array<{
    signal: AbortSignal | undefined;
    onAbort: () => void;
    resolve: (release: () => void) => void;
    reject: (reason: Error) => void;
  }> = [];
  const makeRelease = () => {
    let released = false;
    return () => {
      if (released) return;
      released = true;
      active--;
      const waiter = waiters.shift();
      if (!waiter) return;
      waiter.signal?.removeEventListener("abort", waiter.onAbort);
      active++;
      waiter.resolve(makeRelease());
    };
  };
  return {
    acquire(signal: AbortSignal | undefined): Promise<() => void> {
      if (signal?.aborted) return Promise.reject(new Error("Exploration subagent was aborted while queued"));
      if (active < limit) {
        active++;
        return Promise.resolve(makeRelease());
      }
      return new Promise((resolve, reject) => {
        const waiter = {
          signal,
          resolve,
          reject,
          onAbort: () => {
            const index = waiters.indexOf(waiter);
            if (index >= 0) waiters.splice(index, 1);
            signal?.removeEventListener("abort", waiter.onAbort);
            reject(new Error("Exploration subagent was aborted while queued"));
          },
        };
        waiters.push(waiter);
        signal?.addEventListener("abort", waiter.onAbort, { once: true });
      });
    },
  };
}

// A dispatched role's contract is a rendered agent artifact rather than a literal
// string here, so the durable prose is reviewable and drift-checked. Three
// behaviours are shared by every role that loads one: the missing-file error
// carries an actionable repair, the frontmatter is stripped rather than passed to
// the child, and an empty instruction body is a hard error instead of a silently
// contentless prompt. What varies per role is only the wording, so each caller
// supplies its own noun, repair clause, and prepend.
interface ContractSource {
  relative: string;
  noun: string;
  repair: string;
  prepend: string;
}

async function loadAgentContract(deps: ExtensionDependencies, root: string, source: ContractSource): Promise<string> {
  let content: string;
  try { content = await deps.readFile(join(root, source.relative), "utf8"); }
  catch {
    throw new Error(`Missing Pi ${source.noun} ${source.relative}. ${source.repair}`);
  }
  const parsed = parseFrontmatter<Record<string, unknown>>(content);
  if (!parsed.body.trim()) throw new Error(`Pi ${source.noun} ${source.relative} has no instruction body; run ./awf render.`);
  return `${source.prepend}\n\n${parsed.body}`;
}

function loadReviewer(deps: ExtensionDependencies, root: string, kind: ReviewKind): Promise<string> {
  return loadAgentContract(deps, root, {
    relative: REVIEWER_PATHS[kind],
    noun: "reviewer",
    repair: `Enable the matching ${kind}-reviewer agent and run ./awf render.`,
    prepend: `You are the governed ${kind} reviewer. You are report-only: never edit or commit.`,
  });
}

// The per-role prepend carries the commit authority, which the rendered body
// describes but cannot know for a given call.
function loadImplementer(deps: ExtensionDependencies, root: string, allowCommits: boolean): Promise<string> {
  const authority = allowCommits
    ? "Commits are allowed when the task requests them; you are the phase owner."
    : "Commits are forbidden; do not change HEAD. You are a helper.";
  return loadAgentContract(deps, root, {
    relative: IMPLEMENTER_PATH,
    noun: "implementer",
    repair: "Enable the implementer agent and run ./awf render.",
    prepend: `You are the governed implementation subagent. ${authority}`,
  });
}

function loadExplorer(deps: ExtensionDependencies, root: string): Promise<string> {
  return loadAgentContract(deps, root, {
    relative: EXPLORER_PATH,
    noun: "explorer",
    repair: "Enable the explorer agent and run ./awf render.",
    prepend: "You are the governed exploration subagent. You are report-only: never edit or commit.",
  });
}

function loadGroundingChecker(deps: ExtensionDependencies, root: string): Promise<string> {
  return loadAgentContract(deps, root, {
    relative: GROUNDING_CHECKER_PATH,
    noun: "grounding-checker",
    repair: "Enable the grounding-checker agent and run ./awf render.",
    prepend: "You are the governed grounding-check subagent. You are report-only: never edit or commit.",
  });
}

/* c8 ignore stop */
function stripTerminalLineEnding(value: string): string {
  if (value.endsWith("\r\n")) return value.slice(0, -2);
  if (value.endsWith("\n")) return value.slice(0, -1);
  return value;
}

async function snapshot(pi: ExtensionAPI, cwd: string): Promise<GitSnapshot> {
  const head = await pi.exec("git", ["rev-parse", "HEAD"], { cwd });
  if (head.code !== 0) return { available: false };
  const status = await pi.exec("git", ["status", "--short"], { cwd });
  return { available: status.code === 0, head: head.stdout.trim(), status: status.stdout };
}

async function canonicalPath(deps: ExtensionDependencies, path: string, failureMessage: string): Promise<string> {
  try { return await deps.realpath(path); }
  catch (error) { throw new Error(`${failureMessage}: ${errorText(error)}`, { cause: error }); }
}

async function resolveVerificationCheckout(
  pi: ExtensionAPI, deps: ExtensionDependencies, root: string, requested: string | undefined,
): Promise<string> {
  if (requested === undefined) return root;
  const normalized = requested.startsWith("@") ? requested.slice(1) : requested;
  if (normalized === "") throw new Error("verificationCheckout is empty after removing one leading @; omit the field for root verification or provide a registered checkout root.");
  const candidate = resolve(root, normalized);
  const checkout = await canonicalPath(deps, candidate, `verificationCheckout does not exist: ${candidate}`);
  const canonicalRoot = await canonicalPath(deps, root, "Cannot resolve the project root checkout.");
  const selectedGitEntry = join(checkout, ".git");
  let entry: { isFile(): boolean; isSymbolicLink(): boolean } | undefined;
  try { entry = await deps.lstat(selectedGitEntry); }
  catch (error) {
    if (errorCode(error) !== "ENOENT") throw new Error(`Cannot inspect verificationCheckout .git entry ${selectedGitEntry}: ${errorText(error)}`, { cause: error });
  }
  if (entry?.isSymbolicLink()) throw new Error(`verificationCheckout .git entry must not be a symlink: ${selectedGitEntry}`);

  const top = await pi.exec("git", ["rev-parse", "--show-toplevel"], { cwd: checkout });
  if (top.code !== 0) throw new Error(`verificationCheckout must be a live registered checkout root for this repository: ${checkout}`);
  const topPath = stripTerminalLineEnding(top.stdout);
  const canonicalTop = await canonicalPath(deps, topPath, `verificationCheckout Git root does not exist: ${topPath}`);
  if (canonicalTop !== checkout) throw new Error(`verificationCheckout must name the checkout root, not a subdirectory: ${checkout}`);
  const rootCommon = await pi.exec("git", ["rev-parse", "--path-format=absolute", "--git-common-dir"], { cwd: root });
  const checkoutCommon = await pi.exec("git", ["rev-parse", "--path-format=absolute", "--git-common-dir"], { cwd: checkout });
  if (rootCommon.code !== 0 || checkoutCommon.code !== 0) throw new Error(`verificationCheckout must be a live registered checkout root for this repository: ${checkout}`);
  const canonicalRootCommon = await canonicalPath(deps, stripTerminalLineEnding(rootCommon.stdout), "Cannot resolve the project root Git common directory.");
  const canonicalCheckoutCommon = await canonicalPath(deps, stripTerminalLineEnding(checkoutCommon.stdout), `Cannot resolve verificationCheckout Git common directory: ${checkout}`);
  if (canonicalRootCommon !== canonicalCheckoutCommon) throw new Error(`verificationCheckout must belong to the same repository as the project root: ${checkout}`);

  const gitDirectory = await pi.exec("git", ["rev-parse", "--absolute-git-dir"], { cwd: checkout });
  if (gitDirectory.code !== 0) throw new Error(`Cannot resolve verificationCheckout absolute Git directory: ${checkout}`);
  const canonicalGitDirectory = await canonicalPath(deps, stripTerminalLineEnding(gitDirectory.stdout), `Cannot resolve verificationCheckout absolute Git directory: ${checkout}`);
  if (canonicalGitDirectory === canonicalCheckoutCommon) {
    if (checkout !== canonicalRoot) throw new Error(`verificationCheckout must identify the project root or a live linked checkout, not a copied primary Git pointer: ${checkout}`);
    return checkout;
  }
  let backlink: string;
  try { backlink = await deps.readFile(join(canonicalGitDirectory, "gitdir"), "utf8"); }
  catch (error) {
    if (errorCode(error) === "ENOENT") throw new Error(`verificationCheckout must be a live linked checkout with an administrative backlink: ${checkout}`, { cause: error });
    throw new Error(`Cannot read verificationCheckout administrative backlink for ${checkout}: ${errorText(error)}`, { cause: error });
  }
  if (!entry?.isFile()) throw new Error(`verificationCheckout linked .git entry must be a non-symlink regular file: ${selectedGitEntry}`);
  const backlinkPath = stripTerminalLineEnding(backlink);
  if (backlinkPath === "") throw new Error(`verificationCheckout administrative backlink is empty: ${join(canonicalGitDirectory, "gitdir")}`);
  const canonicalBacklink = await canonicalPath(deps, resolve(canonicalGitDirectory, backlinkPath), `Cannot resolve verificationCheckout administrative backlink for ${checkout}`);
  if (canonicalBacklink !== selectedGitEntry) throw new Error(`verificationCheckout administrative backlink ${canonicalBacklink} does not identify the registered checkout ${checkout}`);
  return checkout;
}
/* c8 ignore start */

function validateTask(task: string): void {
  if (!task.trim()) throw new Error("Subagent task must be a non-empty string");
}

function executionMetadata(
  selected: ReturnType<typeof resolveChildModel>,
  thinkingLevel: ThinkingLevel,
  options: Record<string, string | boolean> = {},
): ExecutionMetadata {
  return {
    resolvedModel: `${selected.model.provider}/${selected.model.id}`,
    requestedModel: selected.requested,
    modelSource: selected.source,
    thinkingLevel,
    options,
  };
}

function stateFor(failed: boolean, stopReason?: string): SubagentState {
  if (!failed) return "completed";
  return stopReason === "aborted" ? "aborted" : "failed";
}

function boundedStopReason(value: string | undefined): "complete" | "length" | "tool" | "error" | "canceled" | "unknown" {
  if (value === "stop" || value === "end") return "complete";
  if (value === "length") return "length";
  if (value === "toolUse" || value === "tool") return "tool";
  if (value === "error") return "error";
  if (value === "aborted" || value === "canceled") return "canceled";
  return "unknown";
}

function toolResult(role: RunRequest["role"], task: string, result: Awaited<ReturnType<Runner["run"]>>, details: Record<string, unknown> = {}) {
  const failed = result.failed; const usage = { input: result.usage.input, output: result.usage.output, cacheRead: result.usage.cacheRead, cacheWrite: result.usage.cacheWrite, totalTokens: result.usage.input + result.usage.output + result.usage.cacheRead + result.usage.cacheWrite, cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0, total: result.usage.cost } };
  return {
    content: [{ type: "text" as const, text: failed ? (result.failureMessage ?? "Subagent failed") : result.output }],
    usage,
    details: {
      role, task, state: stateFor(failed, result.stopReason), events: result.events,
      omittedEvents: result.omittedEvents, ...details, stderr: result.stderr,
      usage: result.usage, model: result.model, modelChanged: result.modelChanged,
      modelMismatch: Boolean(result.model && result.model !== details.resolvedModel),
      latestCacheHitRate: result.latestCacheHitRate, stopReason: result.stopReason,
      ...(failed ? { awfFailure: true as const } : {}),
    },
  };
}

function contentText(result: any): string {
  const part = result.content?.find((item: any) => item?.type === "text");
  return utf8Bound(String(part?.text ?? "(no output)"), MAX_FALLBACK_BYTES, DISPLAY_TRUNCATION);
}

function formatTokens(value: number): string {
  if (value >= 1_000_000) return `${(value / 1_000_000).toFixed(value >= 10_000_000 ? 0 : 1).replace(/\.0$/, "")}m`;
  if (value >= 1_000) return `${(value / 1_000).toFixed(value >= 100_000 ? 0 : 1).replace(/\.0$/, "")}k`;
  return String(value);
}

function compactUsageText(usage: Usage | undefined, latestCacheHitRate: number | undefined): string {
  if (!usage || !(usage.turns || usage.input || usage.output || usage.cacheRead || usage.cacheWrite || usage.cost)) return "";
  const parts = [`${usage.turns} turn${usage.turns === 1 ? "" : "s"}`];
  if (usage.input) parts.push(`↑${formatTokens(usage.input)}`);
  if (usage.output) parts.push(`↓${formatTokens(usage.output)}`);
  if (usage.cacheRead) parts.push(`R${formatTokens(usage.cacheRead)}`);
  if (usage.cacheWrite) parts.push(`W${formatTokens(usage.cacheWrite)}`);
  if (latestCacheHitRate !== undefined) parts.push(`CH${latestCacheHitRate.toFixed(1)}%`);
  if (usage.cost) parts.push(`$${usage.cost.toFixed(3)}`);
  return parts.join(" ");
}

function optionText(options: Readonly<Record<string, string | boolean>> | undefined): string {
  return Object.entries(options ?? {}).map(([key, value]) => `${key}:${value}`).join(" ");
}

function activeModel(details: SubagentDetails): string {
  return details.model ?? details.resolvedModel ?? details.requestedModel ?? "unknown";
}

function eventText(event: DisplayEvent): string {
  if (event.kind === "assistant") return event.text;
  if (event.kind === "tool-start") return `-> ${event.toolName} ${event.argsPreview}`;
  return `<- ${event.toolName} ${event.isError ? "error" : "ok"}`;
}

function callOptions(role: RunRequest["role"], args: any): Record<string, string | boolean> {
  if (role === "explore") return { breadth: args.breadth ?? "?", detail: args.detail ?? "?" };
  if (role === "review") return { kind: args.kind ?? "?" };
  /* c8 ignore stop */
  if (role === "implement") return { allowCommits: args.allowCommits ?? "?", ...(args.verificationCheckout === undefined ? {} : { verificationCheckout: args.verificationCheckout }) };
  /* c8 ignore start */
  return {};
}

function renderSubagentCall(role: RunRequest["role"], args: any, theme: any) {
  const task = utf8Bound(String(args.task ?? ""), MAX_TASK_PREVIEW_BYTES, TASK_TRUNCATION);
  const model = args.model ? String(args.model) : "(configured or inherited)";
  const options = optionText(callOptions(role, args));
  const metadata = [`model:${model}`, options].filter(Boolean).join(" ");
  return new Text(`${theme.fg("toolTitle", theme.bold(`${role} subagent`))}\n${theme.fg("muted", metadata)}\n${theme.fg("dim", task || "(no task)")}`, 0, 0);
}

function renderSubagentResult(role: RunRequest["role"], result: any, options: { expanded: boolean; isPartial: boolean }, theme: any) {
  const details = result.details as SubagentDetails | undefined;
  if (!details || !Array.isArray(details.events)) {
    return new Text(`${theme.fg("toolTitle", theme.bold(`${role} subagent`))}\n${theme.fg("toolOutput", contentText(result))}`, 0, 0);
  }
  const state = details.state;
  const statusColor = state === "completed" ? "success" : state === "queued" || state === "running" ? "warning" : "error";
  const header = `${theme.fg(statusColor, state)} ${theme.fg("toolTitle", theme.bold(`${role} subagent`))}`;
  const actualModel = activeModel(details);
  const resolvedModel = details.resolvedModel ?? actualModel;
  const modelMismatch = details.modelMismatch || Boolean(details.resolvedModel && actualModel !== details.resolvedModel);
  const metadata = [
    `model:${resolvedModel}`,
    details.modelSource ? `source:${details.modelSource}` : "",
    details.resolvedModel && actualModel !== details.resolvedModel ? `actual:${actualModel}` : "",
    modelMismatch ? "model-mismatch" : "",
    details.modelChanged ? "model-changed" : "",
    details.thinkingLevel ? `thinking:${details.thinkingLevel}` : "",
    optionText(details.options),
  ].filter(Boolean).join(" ");
  const usage = compactUsageText(details.usage, details.latestCacheHitRate);
  const omission = details.omittedEvents > 0 ? `${details.omittedEvents} older events omitted` : "no omitted events";

  if (!options.expanded) {
    const retainedSkipped = Math.max(0, details.events.length - COLLAPSED_EVENT_COUNT);
    const events = details.events.slice(-COLLAPSED_EVENT_COUNT).map(eventText);
    const lines = [header, metadata, omission];
    if (retainedSkipped > 0) lines.push(`... ${retainedSkipped} earlier retained events`);
    lines.push(...events);
    if (usage) lines.push(usage);
    if (!options.isPartial && (details.events.length > 0 || details.task)) lines.push(keyHint("app.tools.expand", "to expand"));
    return new Text(lines.join("\n"), 0, 0);
  }

  const container = new Container();
  container.addChild(new Text(header, 0, 0));
  container.addChild(new Spacer(1));
  container.addChild(new Text(theme.fg("muted", "Execution"), 0, 0));
  const modelLines = [`Model: ${actualModel}`];
  if (details.resolvedModel && actualModel !== details.resolvedModel) modelLines.push(`resolved: ${details.resolvedModel}`);
  if (details.modelSource) modelLines.push(`source: ${details.modelSource}`);
  if (details.thinkingLevel) modelLines.push(`Thinking: ${details.thinkingLevel}`);
  if (details.modelMismatch) modelLines.push("actual model differs from resolved model");
  if (details.modelChanged) modelLines.push("model changed during run");
  for (const [key, value] of Object.entries(details.options ?? {})) modelLines.push(`${key}: ${value}`);
  container.addChild(new Text(modelLines.join("\n"), 0, 0));
  container.addChild(new Spacer(1));
  container.addChild(new Text(theme.fg("muted", "Task"), 0, 0));
  container.addChild(new Text(details.task || "(no task)", 0, 0));
  container.addChild(new Spacer(1));
  container.addChild(new Text(theme.fg("muted", `Activity (${omission})`), 0, 0));
  if (details.events.length === 0) container.addChild(new Text("(no activity)", 0, 0));
  for (const event of details.events) container.addChild(new Text(eventText(event), 0, 0));
  if (!options.isPartial) {
    container.addChild(new Spacer(1));
    container.addChild(new Text(theme.fg("muted", state === "completed" ? "Report" : "Failure"), 0, 0));
    container.addChild(new Markdown(contentText(result), 0, 0, getMarkdownTheme()));
  }
  if (details.stderr) {
    container.addChild(new Spacer(1));
    container.addChild(new Text(theme.fg("muted", "Diagnostics"), 0, 0));
    container.addChild(new Text(details.stderr, 0, 0));
  }
  if (details.usage) {
    const breakdown = [
      `Input: ${details.usage.input}`,
      `Output: ${details.usage.output}`,
      `Cache read: ${details.usage.cacheRead}`,
      `Cache write: ${details.usage.cacheWrite}`,
      `Cache hit: ${details.latestCacheHitRate === undefined ? "n/a" : `${details.latestCacheHitRate.toFixed(1)}%`}`,
      `Cost: $${details.usage.cost.toFixed(3)}`,
      `Turns: ${details.usage.turns}`,
    ];
    container.addChild(new Spacer(1));
    container.addChild(new Text(theme.fg("muted", "Usage"), 0, 0));
    container.addChild(new Text(breakdown.join("\n"), 0, 0));
  }
  return container;
}

function renderers(role: RunRequest["role"]) {
  return {
    renderCall(args: any, theme: any) { return renderSubagentCall(role, args, theme); },
    renderResult(result: any, options: { expanded: boolean; isPartial: boolean }, theme: any) { return renderSubagentResult(role, result, options, theme); },
  };
}

function modelLabel(model: any, parent: { provider: string; id: string } | undefined, configured: string | undefined, recommended: string): string {
  const reference = `${model.provider}/${model.id}`;
  const parts = [reference, `- ${model.name}`, `base $${model.cost.input}/$${model.cost.output} per Mtok`];
  const tier = model.cost.tiers?.[0];
  if (tier) parts.push(`tier above ${tier.inputTokensAbove} input tokens $${tier.input}/$${tier.output}`);
  parts.push(`context ${model.contextWindow}`, `max output ${model.maxTokens}`);
  parts.push(model.reasoning ? "reasoning" : "no reasoning");
  parts.push(Array.isArray(model.input) && model.input.includes("image") ? "image" : "text-only");
  if (parent?.provider === model.provider && parent?.id === model.id) parts.push("[current parent]");
  if (configured === reference) parts.push("[configured]");
  if (recommended === reference) parts.push("[recommended]");
  return parts.join(" ");
}

const SLOT_GUIDANCE: Array<{ key: PreferenceField; guidance: string }> = [
  { key: "default", guidance: "Shared fallback for every role; a mid-tier coding model fits." },
  { key: "grounding", guidance: "Grounding verifies designs against source; favor the strongest model." },
  { key: "exploration", guidance: "Exploration fans out cheap reads; favor the cheapest capable model." },
  { key: "review", guidance: "Review judges finished work; favor the strongest model." },
  { key: "implementation", guidance: "Implementation edits code; a mid-tier coding model fits." },
  { key: "small", guidance: "Small is for narrow, mechanical, low-ambiguity work." },
  { key: "standard", guidance: "Standard is for substantive but bounded work." },
  { key: "large", guidance: "Large is for broad, intricate, cross-cutting, or high-consequence work." },
];

export function registerSubagentTools(pi: ExtensionAPI, deps: ExtensionDependencies): void {
  if (!guardMinimumRuntime(pi, deps, ["on", "eventsEmit", "registerTool", "registerCommand", "exec", "getThinkingLevel", "getActiveTools"])) return;

  const root = projectRoot(deps.extensionFile);
  const now = deps.now ?? Date.now;
  const nextObservationId = deps.observationId ?? randomUUID;
  const reloadState = async (ctx: any): Promise<EffectivePreferenceState> => {
    return loadPreferenceState(deps, ctx.modelRegistry);
  };
  const notifyPreferenceState = (ctx: any, state: EffectivePreferenceState): void => {
    const identity = ctx.sessionManager;
    if (!identity || typeof identity !== "object" || preferenceNotices.has(identity)) return;
    if (state.blocked) ctx.ui.notify(`${PREFERENCES_BLOCKED} ${state.errors.join("; ")}. ${PREFERENCES_REPAIR}`, "error");
    else if (state.missing.length > 0) ctx.ui.notify(`Subagent model preferences are incomplete; missing: ${state.missing.join(", ")}. Run /awf-subagent-models to configure roles and tiers.`, "info");
    else return;
    preferenceNotices.add(identity);
  };
  const refreshAndResolve = async (ctx: any, role: RunRequest["role"], requested: string | undefined) => {
    const state = await reloadState(ctx);
    notifyPreferenceState(ctx, state);
    return resolveChildModel(ctx.modelRegistry, ctx.model, role, requested, state);
  };
  pi.on("session_start", async (_event, ctx) => notifyPreferenceState(ctx, await reloadState(ctx)));
  pi.on("before_agent_start", async (event: any, ctx: any) => {
    const selected = Array.isArray(event.systemPromptOptions?.selectedTools) ? event.systemPromptOptions.selectedTools : pi.getActiveTools();
    if (!Array.isArray(selected) || !selected.some((tool: string) => SUBAGENT_TOOL_NAMES.has(tool))) return undefined;
    const state = await reloadState(ctx);
    notifyPreferenceState(ctx, state);
    const card = buildRoutingCard(state);
    if (card.startsWith("[awf subagent routing]\nstate: unavailable")) ctx.ui.notify(ROUTING_CARD_OVERFLOW_WARNING, "error");
    return { systemPrompt: event.systemPrompt + "\n\n" + card };
  });
  pi.registerCommand("awf-subagent-models", {
    description: "Configure per-role subagent model preferences.",
    handler: async (_args: string, ctx: any) => {
      if (ctx.mode !== "tui" || typeof ctx.ui?.select !== "function") {
        ctx.ui?.notify?.("awf-subagent-models requires an interactive TUI session.", "error");
        return;
      }
      const state = await reloadState(ctx);
      const canceled = () => ctx.ui.notify("Subagent model preferences unchanged.", "info");
      const globalLabel = `User-global (${state.global.path})`;
      const scopeChoice = await ctx.ui.select("Preference scope", [globalLabel, `Project-local (${state.project.path})`]);
      if (scopeChoice === undefined) return canceled();
      const scope = scopeChoice === globalLabel ? state.global : state.project;
      let snapshot: string | undefined;
      try { snapshot = await deps.readFile(scope.path, "utf8"); }
      catch (error) {
        if (errorCode(error) !== "ENOENT") { ctx.ui.notify(`Cannot read ${scope.path}: ${errorText(error)}`, "error"); return; }
        snapshot = undefined;
      }
      const scopeInvalid = state.invalid.filter((item) => item.scope === scope.scope);
      const currentLines = scopeInvalid.length > 0 ? scopeInvalid.map(invalidText) : Object.entries(scope.values).map(([key, value]) => `${key}: ${value}`);
      const proceed = await ctx.ui.confirm(
        "Current subagent model preferences",
        `${scope.path}\n${currentLines.join("\n") || "(empty)"}\n\nEffective routing now:\n${routingPreview(state.project, state.global, state).join("\n")}\n\nThis wizard configures child routing only; the parent session remains the mastermind for brainstorming and plan authoring. Configure this scope now?`,
      );
      if (!proceed) return canceled();
      const presetIssues: string[] = [];
      for (const [slot, reference] of Object.entries(RECOMMENDED_PRESET)) {
        const parsed = parseExactModelReference(reference);
        const found = "reason" in parsed ? undefined : ctx.modelRegistry.find(parsed.provider, parsed.id);
        if (!found) presetIssues.push(`preset ${slot} model is unregistered.`);
        else if (!ctx.modelRegistry.hasConfiguredAuth(found)) presetIssues.push(`preset ${slot} model is unauthenticated.`);
      }
      let next: SubagentModelPreferences | undefined;
      if (presetIssues.length === 0) {
        const preset = "Apply recommended GPT-5.6 preset";
        const mode = await ctx.ui.select("Configuration mode", [preset, "Configure each slot"]);
        if (mode === undefined) return canceled();
        if (mode === preset) next = { ...RECOMMENDED_PRESET };
      } else {
        ctx.ui.notify(`Recommended preset unavailable: ${presetIssues.join(" ")}`, "info");
      }
      if (next === undefined) {
        const chosen: SubagentModelPreferences = {};
        const unset = "leave unset (use fallback chain)";
        for (const slot of SLOT_GUIDANCE) {
          const options = [unset, ...ctx.modelRegistry.getAll().map((model: any) => modelLabel(model, ctx.model, scope.values[slot.key], RECOMMENDED_PRESET[slot.key]))];
          const picked = await ctx.ui.select(`${slot.key}: ${slot.guidance}`, options);
          if (picked === undefined) return canceled();
          if (picked !== unset) (chosen as Record<string, string>)[slot.key] = picked.split(" ")[0];
        }
        next = chosen;
      }
      const content = `${JSON.stringify(next, null, 2)}\n`;
      const nextScope: PreferenceSourceState = { ...scope, values: next, invalid: [] };
      const previewGlobal = scope.scope === "global" ? nextScope : state.global;
      const previewProject = scope.scope === "project" ? nextScope : state.project;
      const previewState = effectivePreferenceState(previewGlobal, previewProject, registryFailures(ctx.modelRegistry, [previewGlobal, previewProject]));
      const preview = routingPreview(previewProject, previewGlobal, previewState);
      const confirmed = await ctx.ui.confirm("Save subagent model preferences", `${scope.path}\n${content}\nEffective routing after save:\n${preview.join("\n")}\n\nWrite this file?`);
      if (!confirmed) return canceled();
      if (scope.scope === "project") {
        const workTree = await pi.exec("git", ["rev-parse", "--is-inside-work-tree"], { cwd: root });
        if (workTree.code !== 0) {
          ctx.ui.notify("Not a git work tree; skipping ignore check.", "info");
        } else {
          const relative = `${deps.configDirName}/${LOCAL_PREFERENCES_FILE}`;
          const ignored = await pi.exec("git", ["check-ignore", "-q", relative], { cwd: root });
          if (ignored.code !== 0) {
            const append = await ctx.ui.confirm("Gitignore rule required", `${relative} is not ignored. Append the rule to the project root .gitignore?`);
            if (!append) { ctx.ui.notify("Save canceled: the project-local preference file must be gitignored.", "error"); return; }
            const gitignorePath = join(root, ".gitignore");
            let existing = "";
            try { existing = await deps.readFile(gitignorePath, "utf8"); }
            catch (error) {
              if (errorCode(error) !== "ENOENT") { ctx.ui.notify(`Cannot read ${gitignorePath}: ${errorText(error)}`, "error"); return; }
            }
            const separator = existing === "" || existing.endsWith("\n") ? "" : "\n";
            try { await deps.writeFile(gitignorePath, `${existing}${separator}${relative}\n`, { mode: 0o644 }); }
            catch (error) { ctx.ui.notify(`Cannot update ${gitignorePath}: ${errorText(error)}`, "error"); return; }
          }
        }
      }
      try { await deps.mkdir(dirname(scope.path), { recursive: true }); }
      catch (error) { ctx.ui.notify(`Cannot create ${dirname(scope.path)}: ${errorText(error)}`, "error"); return; }
      let latest: string | undefined;
      try { latest = await deps.readFile(scope.path, "utf8"); }
      catch (error) {
        if (errorCode(error) !== "ENOENT") { ctx.ui.notify(`Cannot re-read ${scope.path}: ${errorText(error)}`, "error"); return; }
        latest = undefined;
      }
      if (latest !== snapshot) {
        ctx.ui.notify(`Save canceled: ${scope.path} was modified concurrently; rerun /awf-subagent-models.`, "error");
        return;
      }
      const temp = `${scope.path}.${nextObservationId()}.tmp`;
      try {
        await deps.writeFile(temp, content, { mode: 0o600 });
        await deps.rename(temp, scope.path);
      } catch (error) {
        try { await deps.unlink(temp); } catch { /* best-effort temp cleanup */ }
        ctx.ui.notify(`Save failed: ${errorText(error)}`, "error");
        return;
      }
      const saved = await loadPreferenceState(deps, ctx.modelRegistry);
      if (saved.blocked) {
        ctx.ui.notify(`Preferences saved, but they are invalid and block implicit routing: ${saved.errors.join(" ")} ${PREFERENCES_REPAIR}`, "error");
        return;
      }
      ctx.ui.notify("Subagent model preferences saved.", "info");
    },
  });
  const explorationLimiter = createLimiter(MAX_EXPLORATION_CONCURRENCY);
  let implementationTail: Promise<void> = Promise.resolve();
  const emptyUsage = (): Usage => ({ input: 0, output: 0, cacheRead: 0, cacheWrite: 0, cost: 0, turns: 0 });
  const publishState = (
    onUpdate: ((value: any) => void) | undefined,
    role: RunRequest["role"], task: string, state: "queued" | "running", metadata: ExecutionMetadata,
  ): void => onUpdate?.({
    content: [{ type: "text", text: "(running...)" }],
    details: { role, task, state, events: [], omittedEvents: 0, usage: emptyUsage(), ...metadata },
  });
  const run = async (
    role: RunRequest["role"], task: string, tools: readonly string[], systemPrompt: string,
    model: { provider: string; id: string }, metadata: ExecutionMetadata,
    signal: AbortSignal | undefined, onUpdate: ((value: any) => void) | undefined,
    queuedAt: number,
  ) => {
    validateTask(task);
    const runStartedAt = now();
    publishState(onUpdate, role, task, "running", metadata);
    let result: Awaited<ReturnType<Runner["run"]>>;
    try {
      result = await deps.runner.run({
        role, task, cwd: root, model, thinkingLevel: metadata.thinkingLevel,
        tools, systemPrompt, signal,
        onUpdate: (update) => onUpdate?.({
          content: [{ type: "text", text: "(running...)" }],
          details: {
            role, task, state: "running", events: update.events, omittedEvents: update.omittedEvents,
            usage: update.usage, model: update.model, modelChanged: update.modelChanged,
            modelMismatch: Boolean(update.model && update.model !== metadata.resolvedModel),
            latestCacheHitRate: update.latestCacheHitRate, ...metadata,
          },
        }),
      });
    } catch (error) {
      throw error;
    }
    const completedAt = now();
    return result;
  };

  pi.on("tool_call", (event, ctx) => {
    const leaf = ctx.sessionManager.getLeafEntry();
    const content = leaf?.type === "message" && leaf.message?.role === "assistant" && Array.isArray(leaf.message.content)
      ? leaf.message.content
      : [];
    const calls = content.filter((item: any) => item?.type === "toolCall");
    const correlated = calls.some((call: any) => call.id === event.toolCallId && call.name === event.toolName);
    if (!correlated) return event.toolName === "subagent_implement"
      ? { block: true, reason: "Cannot verify the current tool batch; retry subagent_implement alone." }
      : undefined;
    if (calls.length > 1 && calls.some((call: any) => call.name === "subagent_implement"))
      return { block: true, reason: "A batch containing subagent_implement cannot contain siblings; retry subagent_implement alone." };
    return undefined;
  });

  pi.on("tool_result", (event) => {
    const details = event.details as SubagentDetails | undefined;
    if (SUBAGENT_TOOL_NAMES.has(event.toolName) && details?.awfFailure === true) return { isError: true };
  });

  pi.registerTool({
    name: "subagent_grounding",
    label: "Grounding Subagent",
    description: "Run one fresh-context, no-mutation grounding check. Omit model for configured or inherited routing; use an exact tier provider/model-id only for deliberate override. Omission is the only default form.",
    promptSnippet: "Ground an agreed design against source and project constraints",
    promptGuidelines: ["Use subagent_grounding whenever the rendered grounding support contract calls for repository-premise checks; include the complete grounding brief in task. Omit model for configured or inherited routing; use the selected tier's exact provider/model-id only for deliberate override. Omit the model field to use configured or inherited routing."],
    parameters: Type.Object({ task: Type.String({ minLength: 1 }), model: Type.Optional(MODEL_REFERENCE_SCHEMA) }, { additionalProperties: false }),
    async execute(_id, params, signal, onUpdate, ctx) {
      validateTask(params.task);
      const thinkingLevel = pi.getThinkingLevel() as ThinkingLevel;
      const selected = await refreshAndResolve(ctx, "grounding", params.model);
      const metadata = executionMetadata(selected, thinkingLevel);
      const queuedAt = now();
      const contract = await loadGroundingChecker(deps, root);
      return toolResult("grounding", params.task, await run("grounding", params.task, GROUNDING_TOOLS, contract, selected.model, metadata, signal, onUpdate, queuedAt), metadata);
    },
    ...renderers("grounding"),
  });

  pi.registerTool({
    name: "subagent_explore",
    label: "Explore Subagent",
    description: "Run one fresh-context, no-mutation exploration child. Omit model for configured or inherited routing; use an exact tier provider/model-id only for deliberate override. Omission is the only default form.",
    promptSnippet: "Delegate a self-contained read-oriented investigation to fresh context",
    promptGuidelines: ["Use subagent_explore for one scoped investigation; include all required context in task. Omit model for configured or inherited routing; use the selected tier's exact provider/model-id only for deliberate override. Omit the model field to use configured or inherited routing."],
    parameters: Type.Object({
      task: Type.String({ minLength: 1 }),
      breadth: StringEnum(["targeted", "bounded", "broad"] as const),
      detail: StringEnum(["paths", "summary", "analysis"] as const),
      model: Type.Optional(MODEL_REFERENCE_SCHEMA),
    }, { additionalProperties: false }),
    async execute(_id, params, signal, onUpdate, ctx) {
      validateTask(params.task);
      const thinkingLevel = pi.getThinkingLevel() as ThinkingLevel;
      const selected = await refreshAndResolve(ctx, "explore", params.model);
      const metadata = executionMetadata(selected, thinkingLevel, { breadth: params.breadth, detail: params.detail });
      publishState(onUpdate, "explore", params.task, "queued", metadata);
      const queuedAt = now();
      const release = await explorationLimiter.acquire(signal);
      try {
        const finalSelected = await refreshAndResolve(ctx, "explore", params.model);
        const finalMetadata = executionMetadata(finalSelected, thinkingLevel, { breadth: params.breadth, detail: params.detail });
        const contract = [
          await loadExplorer(deps, root),
          `Selected breadth maximum: ${params.breadth}`,
          `Selected report detail: ${params.detail}`,
          "Pi admits at most ten active exploration children and queues the rest FIFO with abort-aware removal.",
        ].join("\n");
        return toolResult("explore", params.task, await run("explore", params.task, EXPLORE_TOOLS, contract, finalSelected.model, finalMetadata, signal, onUpdate, queuedAt), finalMetadata);
      } finally {
        release();
      }
    },
    ...renderers("explore"),
  });

  pi.registerTool({
    name: "subagent_review",
    label: "Review Subagent",
    description: "Run one governed report-only ADR, plan, or code reviewer in fresh context. Omit model for configured or inherited routing; use an exact tier provider/model-id only for deliberate override. Omission is the only default form.",
    promptSnippet: "Delegate governed ADR, plan, or code review to fresh context",
    promptGuidelines: ["Use subagent_review with kind adr, plan, or code and a self-contained review brief. Omit model for configured or inherited routing; use the selected tier's exact provider/model-id only for deliberate override. Omit the model field to use configured or inherited routing."],
    parameters: Type.Object({
      kind: StringEnum(["adr", "plan", "code"] as const),
      task: Type.String({ minLength: 1 }),
      model: Type.Optional(MODEL_REFERENCE_SCHEMA),
    }, { additionalProperties: false }),
    async execute(_id, params, signal, onUpdate, ctx) {
      validateTask(params.task);
      const thinkingLevel = pi.getThinkingLevel() as ThinkingLevel;
      const prompt = await loadReviewer(deps, root, params.kind);
      const selected = await refreshAndResolve(ctx, "review", params.model);
      const metadata = executionMetadata(selected, thinkingLevel, { kind: params.kind });
      const queuedAt = now();
      return toolResult("review", params.task, await run("review", params.task, REVIEW_TOOLS, prompt, selected.model, metadata, signal, onUpdate, queuedAt), { ...metadata, kind: params.kind });
    },
    ...renderers("review"),
  });

  /* c8 ignore stop */
  pi.registerTool({
    name: "subagent_implement",
    label: "Implementation Subagent",
    description: "Run one serialized implementation child while verifying commit policy in the caller-selected project checkout. Call this tool alone in its parent tool batch. Omit verificationCheckout for the project root. Omit model for configured or inherited routing; use an exact tier provider/model-id only for deliberate override. Omission is the only model default form.",
    promptSnippet: "Delegate one sequential implementation task to fresh context",
    promptGuidelines: ["Call subagent_implement alone in a tool batch, never in parallel; set allowCommits explicitly. Set verificationCheckout when implementation intentionally targets a managed worktree; this changes verification identity only, not parent or child CWD. Omit it for root work. Omit model for configured or inherited routing; use the selected tier's exact provider/model-id only for deliberate override. Omit the model field to use configured or inherited routing."],
    parameters: Type.Object({
      task: Type.String({ minLength: 1 }),
      allowCommits: Type.Boolean(),
      verificationCheckout: Type.Optional(Type.String()),
      model: Type.Optional(MODEL_REFERENCE_SCHEMA),
    }, { additionalProperties: false }),
    async execute(_id, params, signal, onUpdate, ctx) {
      validateTask(params.task);
      const thinkingLevel = pi.getThinkingLevel() as ThinkingLevel;
      const selected = await refreshAndResolve(ctx, "implement", params.model);
      const metadata = executionMetadata(selected, thinkingLevel, { allowCommits: params.allowCommits, ...(params.verificationCheckout === undefined ? {} : { verificationCheckout: params.verificationCheckout }) });
      const queuedAt = now();
      let release!: () => void;
      const previous = implementationTail;
      implementationTail = new Promise<void>((resolve) => { release = resolve; });
      publishState(onUpdate, "implement", params.task, "queued", metadata);
      await previous;
      try {
        if (signal?.aborted) throw new Error("Implementation subagent was aborted while queued");
        const verificationCheckout = await resolveVerificationCheckout(pi, deps, root, params.verificationCheckout);
        const before = await snapshot(pi, verificationCheckout);
        const finalSelected = await refreshAndResolve(ctx, "implement", params.model);
        const finalMetadata = executionMetadata(finalSelected, thinkingLevel, { allowCommits: params.allowCommits, verificationCheckout });
        const contract = await loadImplementer(deps, root, params.allowCommits);
        const result = await run("implement", params.task, IMPLEMENT_TOOLS, contract, finalSelected.model, finalMetadata, signal, onUpdate, queuedAt);
        const after = await snapshot(pi, verificationCheckout);
        const comparable = before.available && after.available;
        const committedWhenForbidden = !params.allowCommits && comparable && before.head !== after.head;
        // A commit-capable owner that left HEAD alone did not complete its phase.
        // This detects the absence of a commit, not the absence of a reason, so a
        // child that stopped correctly with a full inventory also lands here: that
        // phase did not complete, and a failure result is the honest report. An
        // already-failed or aborted run lands here too, and keeps its own
        // diagnostic ahead of the demand rather than being relabelled.
        const missingCommitWhenOwner = params.allowCommits && comparable && before.head === after.head;
        const gitDetails = { ...finalMetadata, allowCommits: params.allowCommits, verificationCheckout, before, after, commitVerification: comparable ? "verified" : "unavailable" };
        if (committedWhenForbidden) {
          const failure = {
            ...result,
            failed: true,
            failureMessage: `Implementation committed despite allowCommits=false (HEAD ${before.head} -> ${after.head}) in verification checkout ${verificationCheckout}; changes were not reverted.`,
          };
          return toolResult("implement", params.task, failure, gitDetails);
        }
        if (missingCommitWhenOwner) {
          // The child's own account is the point of the whole exercise, and a
          // failed result renders only failureMessage, so carry it into the
          // message rather than replacing it with the demand. An already-failed
          // run contributes its failureMessage; a normal one contributes output.
          const demand = `Implementation was commit-capable but created no commit in ${verificationCheckout} (HEAD unchanged at ${before.head}). If work occurred in another registered worktree, retry with verificationCheckout set to that checkout root. A stopped report must carry the working-tree status, work completed, work remaining, the named failing check with its actual output, and what was already tried.`;
          const failure = {
            ...result,
            failed: true,
            failureMessage: truncateFailure([(result.failureMessage ?? result.output).trim(), demand].filter(Boolean).join("\n\n")),
          };
          return toolResult("implement", params.task, failure, gitDetails);
        }
        return toolResult("implement", params.task, result, gitDetails);
      } finally { release(); }
    },
    ...renderers("implement"),
  });
  /* c8 ignore start */
}

export default async function (pi: ExtensionAPI): Promise<void> {
  const packageJSON = JSON.parse(await readFile(join(getPackageDir(), "package.json"), "utf8")) as { version: string };
  registerSubagentTools(pi, {
    readFile,
    runner: createRunner(productionRunnerDependencies),
    packageVersion: packageJSON.version,
    extensionFile: fileURLToPath(import.meta.url),
    agentDir: getAgentDir(),
    configDirName: CONFIG_DIR_NAME,
    writeFile: (path, data, options) => writeFile(path, data, options),
    mkdir,
    rename,
    unlink,
    realpath,
    lstat,
  });
}

/* c8 ignore stop */
