// GENERATED by awf: do not edit; change .awf/ and run `awf render`
// @ts-nocheck
import { join, resolve, dirname } from "node:path";
import { Type } from "typebox";

export const PREFERENCE_ROLES = ["grounding", "exploration", "review", "implementation"] as const;
export const PREFERENCE_TIERS = ["small", "standard", "large"] as const;
export const PREFERENCE_FIELDS = ["default", ...PREFERENCE_ROLES, ...PREFERENCE_TIERS] as const;
type PreferenceRole = (typeof PREFERENCE_ROLES)[number];
export type PreferenceField = (typeof PREFERENCE_FIELDS)[number];
type SubagentRole = "grounding" | "explore" | "review" | "implement";
export type ModelSource = "inherited" | "requested" | "project-role" | "global-role" | "project-default" | "global-default";
type SourceScope = "global" | "project";
type SourceReason = "read-error" | "malformed-json" | "non-object" | "unknown-key";
type FieldReason = "malformed" | "overlong" | "unregistered" | "unauthenticated" | "unavailable";
type InvalidState =
  | { kind: "source"; scope: SourceScope; reason: SourceReason }
  | { kind: "field"; scope: SourceScope; field: PreferenceField; reason: FieldReason };
export interface SubagentModelPreferences {
  default?: string; grounding?: string; exploration?: string; review?: string; implementation?: string;
  small?: string; standard?: string; large?: string;
}
export interface PreferenceSourceState {
  path: string;
  scope: SourceScope;
  values: SubagentModelPreferences;
  invalid: InvalidState[];
}
export interface EffectivePreferenceState {
  global: PreferenceSourceState;
  project: PreferenceSourceState;
  effective: Partial<Record<PreferenceField, { reference: string; scope: SourceScope }>>;
  missing: PreferenceField[];
  invalid: InvalidState[];
  blocked: boolean;
  errors: string[];
}
interface ModelRegistryLike {
  find(provider: string, id: string): unknown;
  hasConfiguredAuth(model: unknown): boolean;
  getAvailable(): readonly { provider: string; id: string }[];
}
interface PreferenceStoreDependencies {
  readFile(path: string, encoding: "utf8"): Promise<string>;
  extensionFile: string;
  agentDir: string;
  configDirName: string;
}

export const ROLE_PREFERENCE_KEYS: Record<SubagentRole, PreferenceRole> = {
  grounding: "grounding", explore: "exploration", review: "review", implement: "implementation",
};
export const GLOBAL_PREFERENCES_FILE = "awf-subagents.json";
export const LOCAL_PREFERENCES_FILE = "awf-subagents.local.json";
export const RECOMMENDED_PRESET: Required<SubagentModelPreferences> = {
  default: "openai-codex/gpt-5.6-terra",
  grounding: "openai-codex/gpt-5.6-sol",
  exploration: "openai-codex/gpt-5.6-luna",
  review: "openai-codex/gpt-5.6-sol",
  implementation: "openai-codex/gpt-5.6-terra",
  small: "openai-codex/gpt-5.6-luna",
  standard: "openai-codex/gpt-5.6-terra",
  large: "openai-codex/gpt-5.6-sol",
};
export const PREFERENCES_BLOCKED = "Subagent model preferences are invalid; implicit routing is blocked.";
export const PREFERENCES_REPAIR = "Run /awf-subagent-models to repair. Explicit per-call model arguments remain available.";
export const MODEL_FIELD_REPAIR = "Omit the model field to use configured or inherited routing.";
const MODEL_REFERENCE_PATTERN = "^[\\x21-\\x2E\\x30-\\x7E]+/[\\x21-\\x7E]+$";
const MODEL_REFERENCE_FORM = new RegExp(MODEL_REFERENCE_PATTERN);
export const MODEL_REFERENCE_SCHEMA = Type.String({
  minLength: 3,
  maxLength: 256,
  pattern: MODEL_REFERENCE_PATTERN,
  description: "Exact provider/model-id in printable ASCII. Omit the model field to use configured or inherited routing; default, auto, and inherit parent are invalid.",
});
export const ROUTING_CARD_OVERFLOW_WARNING = "awf subagent routing card exceeded 4096 UTF-8 bytes; injected a failure card. Run /awf-subagent-models and retry.";
const FAILURE_CARD = "[awf subagent routing]\nstate: unavailable (routing card exceeded 4096 UTF-8 bytes)\nrepair: Run /awf-subagent-models and retry; implicit routing remains strict.";
const PREFERENCE_KEYS = new Set<string>(PREFERENCE_FIELDS);
const SOURCE_REASON_ORDER: SourceReason[] = ["read-error", "malformed-json", "non-object", "unknown-key"];

function projectRoot(extensionFile: string): string { return resolve(dirname(extensionFile), "../../.."); }
function errorCode(error: unknown): string | undefined { return typeof error === "object" && error !== null ? (error as { code?: string }).code : undefined; }
export function emptyPreferenceSource(scope: SourceScope, path: string): PreferenceSourceState { return { scope, path, values: {}, invalid: [] }; }
export function parseExactModelReference(value: unknown): { provider: string; id: string } | { reason: "malformed" | "overlong" } {
  if (typeof value !== "string") return { reason: "malformed" };
  if (Array.from(value).length > 256) return { reason: "overlong" };
  // Sentinel values are rejected explicitly, not incidentally. The shared form check below already
  // subsumes all three, but keeping this line means a later charset change cannot silently accept
  // one of them.
  if (value === "default" || value === "auto" || value === "inherit parent") return { reason: "malformed" };
  if (!MODEL_REFERENCE_FORM.test(value)) return { reason: "malformed" };
  const slash = value.indexOf("/");
  return { provider: value.slice(0, slash), id: value.slice(slash + 1) };
}
export function parsePreferenceSource(scope: SourceScope, path: string, raw: string): PreferenceSourceState {
  const source = emptyPreferenceSource(scope, path);
  let parsed: unknown;
  try { parsed = JSON.parse(raw); }
  catch { source.invalid.push({ kind: "source", scope, reason: "malformed-json" }); return source; }
  if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
    source.invalid.push({ kind: "source", scope, reason: "non-object" });
    return source;
  }
  if (Object.keys(parsed).some((key) => !PREFERENCE_KEYS.has(key))) {
    source.invalid.push({ kind: "source", scope, reason: "unknown-key" });
    return source;
  }
  for (const field of PREFERENCE_FIELDS) {
    const value = (parsed as Record<string, unknown>)[field];
    if (value === undefined) continue;
    const reference = parseExactModelReference(value);
    if ("reason" in reference) source.invalid.push({ kind: "field", scope, field, reason: reference.reason });
    else (source.values as Record<string, string>)[field] = value as string;
  }
  return source;
}
export function invalidText(value: InvalidState): string {
  return value.kind === "source" ? `${value.scope}:source:${value.reason}` : `${value.scope}:${value.field}:${value.reason}`;
}
function sortInvalid(left: InvalidState, right: InvalidState): number {
  const scope = (left.scope === "global" ? 0 : 1) - (right.scope === "global" ? 0 : 1);
  if (scope !== 0) return scope;
  if (left.kind !== right.kind) return left.kind === "source" ? -1 : 1;
  if (left.kind === "source" && right.kind === "source") return SOURCE_REASON_ORDER.indexOf(left.reason) - SOURCE_REASON_ORDER.indexOf(right.reason);
  return PREFERENCE_FIELDS.indexOf((left as Extract<InvalidState, { kind: "field" }>).field)
    - PREFERENCE_FIELDS.indexOf((right as Extract<InvalidState, { kind: "field" }>).field);
}
function registryReason(registry: ModelRegistryLike, reference: string): FieldReason | undefined {
  const parsed = parseExactModelReference(reference);
  if ("reason" in parsed) return parsed.reason;
  const found = registry.find(parsed.provider, parsed.id);
  if (!found) return "unregistered";
  if (!registry.hasConfiguredAuth(found)) return "unauthenticated";
  if (!registry.getAvailable().some((model) => model.provider === parsed.provider && model.id === parsed.id)) return "unavailable";
  return undefined;
}
function requireExactModel(registry: ModelRegistryLike, reference: unknown): { provider: string; id: string } {
  const parsed = parseExactModelReference(reference);
  if ("reason" in parsed) throw new Error(`Subagent model is ${parsed.reason === "overlong" ? "longer than 256 characters" : "not an exact provider/model-id"}. ${MODEL_FIELD_REPAIR}`);
  const reason = registryReason(registry, reference as string);
  if (reason) throw new Error(`Subagent model is ${reason}. ${MODEL_FIELD_REPAIR}`);
  return parsed;
}
export function registryFailures(registry: ModelRegistryLike, sources: PreferenceSourceState[]): InvalidState[] {
  const invalid: InvalidState[] = [];
  for (const source of sources) for (const field of PREFERENCE_FIELDS) {
    const reference = source.values[field];
    if (reference === undefined) continue;
    const reason = registryReason(registry, reference);
    if (reason) invalid.push({ kind: "field", scope: source.scope, field, reason });
  }
  return invalid;
}
export function effectivePreferenceState(global: PreferenceSourceState, project: PreferenceSourceState, registryInvalid: InvalidState[]): EffectivePreferenceState {
  const effective: EffectivePreferenceState["effective"] = {};
  for (const field of PREFERENCE_FIELDS) {
    if (project.values[field] !== undefined) effective[field] = { reference: project.values[field]!, scope: "project" };
    else if (global.values[field] !== undefined) effective[field] = { reference: global.values[field]!, scope: "global" };
  }
  const invalid = [...global.invalid, ...project.invalid, ...registryInvalid].sort(sortInvalid);
  const missing = PREFERENCE_FIELDS.filter((field) => effective[field] === undefined);
  return { global, project, effective, missing, invalid, blocked: invalid.length > 0, errors: invalid.map(invalidText) };
}
export async function loadPreferenceState(deps: PreferenceStoreDependencies, registry: ModelRegistryLike): Promise<EffectivePreferenceState> {
  const globalPath = join(deps.agentDir, GLOBAL_PREFERENCES_FILE);
  const projectPath = join(projectRoot(deps.extensionFile), deps.configDirName, LOCAL_PREFERENCES_FILE);
  const read = async (scope: SourceScope, path: string): Promise<PreferenceSourceState> => {
    try { return parsePreferenceSource(scope, path, await deps.readFile(path, "utf8")); }
    catch (error) {
      if (errorCode(error) === "ENOENT") return emptyPreferenceSource(scope, path);
      return { ...emptyPreferenceSource(scope, path), invalid: [{ kind: "source", scope, reason: "read-error" }] };
    }
  };
  const global = await read("global", globalPath);
  const project = await read("project", projectPath);
  return effectivePreferenceState(global, project, registryFailures(registry, [global, project]));
}
export function preferredReference(project: PreferenceSourceState, global: PreferenceSourceState, role: SubagentRole): { value: string; source: ModelSource } | undefined {
  const key = ROLE_PREFERENCE_KEYS[role];
  const candidates: Array<{ value: string | undefined; source: ModelSource }> = [
    { value: project.values[key], source: "project-role" }, { value: global.values[key], source: "global-role" },
    { value: project.values.default, source: "project-default" }, { value: global.values.default, source: "global-default" },
  ];
  return candidates.find((candidate) => candidate.value !== undefined) as { value: string; source: ModelSource } | undefined;
}
export function routingPreview(project: PreferenceSourceState, global: PreferenceSourceState, state?: EffectivePreferenceState): string[] {
  const roles = PREFERENCE_ROLES.map((key) => {
    const role = (Object.keys(ROLE_PREFERENCE_KEYS) as SubagentRole[]).find((candidate) => ROLE_PREFERENCE_KEYS[candidate] === key)!;
    const preferred = preferredReference(project, global, role);
    return `${key}: ${preferred ? `${preferred.value} (${preferred.source})` : "parent (inherited)"}`;
  });
  const tiers = PREFERENCE_TIERS.map((key) => `${key}: ${project.values[key] ?? global.values[key] ?? "unset"}`);
  const current = state ?? { missing: PREFERENCE_FIELDS.filter((field) => project.values[field] === undefined && global.values[field] === undefined), invalid: [...global.invalid, ...project.invalid] };
  return ["Role defaults:", ...roles, "Tier mappings:", ...tiers, `Missing: ${current.missing.length ? current.missing.join(", ") : "none"}`, `Invalid: ${current.invalid.length ? current.invalid.map(invalidText).join(", ") : "none"}`];
}
export function resolveChildModel(registry: ModelRegistryLike, parent: { provider: string; id: string } | undefined, role: SubagentRole, requested: string | undefined, state: EffectivePreferenceState): { model: { provider: string; id: string }; requested: string | undefined; source: ModelSource } {
  if (requested !== undefined) return { model: requireExactModel(registry, requested), requested, source: "requested" };
  if (state.blocked) throw new Error(`${PREFERENCES_BLOCKED} ${state.errors.join("; ")}. ${PREFERENCES_REPAIR}`);
  const preferred = preferredReference(state.project, state.global, role);
  if (preferred) return { model: requireExactModel(registry, preferred.value), requested: undefined, source: preferred.source };
  if (!parent) throw new Error("Cannot start a subagent without an active parent model");
  return { model: { provider: parent.provider, id: parent.id }, requested: undefined, source: "inherited" };
}
export function buildRoutingCard(state: EffectivePreferenceState): string {
  const effective = (field: PreferenceField) => state.effective[field]?.reference ?? "missing";
  const role = (field: PreferenceRole) => state.effective[field]?.reference ?? state.effective.default?.reference ?? "missing";
  const invalid = state.invalid.length ? state.invalid.map(invalidText).join("; ") : "none";
  const lines = [
    "[awf subagent routing]", `default: ${effective("default")}`,
    `roles: grounding=${role("grounding")}; exploration=${role("exploration")}; review=${role("review")}; implementation=${role("implementation")}`,
    `tiers: small=${effective("small")}; standard=${effective("standard")}; large=${effective("large")}`,
    `missing: ${state.missing.length ? state.missing.join(", ") : "none"}`, `invalid: ${invalid}`,
  ];
  if (invalid !== "none") lines.push("repair: Run /awf-subagent-models; omit model only after invalid preferences are repaired.");
  lines.push("selection: omit model for the role default; otherwise override deliberately with the selected tier's exact provider/model-id.");
  const card = lines.join("\n");
  return Buffer.byteLength(card, "utf8") <= 4096 ? card : FAILURE_CARD;
}
