// GENERATED by awf: do not edit; change .awf/ and run `awf render`
// @ts-nocheck
import { spawn as nodeSpawn } from "node:child_process";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { basename, join } from "node:path";

export type Role = "grounding" | "explore" | "review" | "implement";
export type ChildSignal = "SIGTERM" | "SIGKILL";
export type ThinkingLevel = "off" | "minimal" | "low" | "medium" | "high" | "xhigh" | "max";

export const MAX_OUTPUT_BYTES = 50 * 1024;
export const MAX_OUTPUT_LINES = 2000;
export const MAX_STDERR_BYTES = 50 * 1024;
export const MAX_DISPLAY_EVENTS = 20;
export const MAX_DISPLAY_EVENT_BYTES = 2 * 1024;
export const MAX_FAILURE_BYTES = 2 * 1024;
export const KILL_DELAY_MS = 5000;

export interface SpawnedProcess {
  stdout: NodeJS.ReadableStream;
  stderr: NodeJS.ReadableStream;
  once(event: "close", listener: (code: number | null) => void): this;
  once(event: "error", listener: (error: Error) => void): this;
  kill(signal: ChildSignal): boolean;
}

export interface SpawnOptions {
  cwd: string;
  shell: false;
  stdio: ["ignore", "pipe", "pipe"];
}

export interface RunnerDependencies {
  spawn(command: string, args: readonly string[], options: SpawnOptions): SpawnedProcess;
  mkdtemp(prefix: string): Promise<string>;
  writeFile(path: string, content: string, options: { encoding: "utf8"; mode: number }): Promise<void>;
  rm(path: string, options: { recursive: true; force: true }): Promise<void>;
  setTimer(callback: () => void, delayMs: number): ReturnType<typeof setTimeout>;
  clearTimer(timer: ReturnType<typeof setTimeout>): void;
  argv: readonly string[];
  execPath: string;
  tempRoot: string;
}

export interface RunRequest {
  role: Role;
  task: string;
  cwd: string;
  model: { provider: string; id: string };
  thinkingLevel: ThinkingLevel;
  tools: readonly string[];
  systemPrompt: string;
  signal?: AbortSignal;
  onUpdate?: (update: RunUpdate) => void;
}

export type DisplayEvent =
  | { sequence: number; kind: "assistant"; text: string }
  | { sequence: number; kind: "tool-start"; toolCallId: string; toolName: string; argsPreview: string }
  | { sequence: number; kind: "tool-end"; toolCallId: string; toolName: string; isError: boolean };
type DisplayEventInput =
  | { kind: "assistant"; text: string }
  | { kind: "tool-start"; toolCallId: string; toolName: string; argsPreview: string }
  | { kind: "tool-end"; toolCallId: string; toolName: string; isError: boolean };
export interface Usage { input: number; output: number; cacheRead: number; cacheWrite: number; cost: number; turns: number; }
export interface RunUpdate {
  events: readonly DisplayEvent[];
  omittedEvents: number;
  usage: Usage;
  model?: string;
  modelChanged: boolean;
  latestCacheHitRate?: number;
}
export interface RunResult {
  output: string;
  stderr: string;
  events: readonly DisplayEvent[];
  omittedEvents: number;
  usage: Usage;
  model?: string;
  modelChanged: boolean;
  latestCacheHitRate?: number;
  stopReason?: string;
  toolCount?: number;
  toolFailureCount?: number;
  failed: boolean;
  failureMessage?: string;
}
export interface Runner { run(request: RunRequest): Promise<RunResult>; }

const emptyUsage = (): Usage => ({ input: 0, output: 0, cacheRead: 0, cacheWrite: 0, cost: 0, turns: 0 });

function utf8Prefix(value: string, maximum: number): string {
  if (Buffer.byteLength(value, "utf8") <= maximum) return value;
  let end = Math.min(value.length, maximum);
  while (end > 0 && Buffer.byteLength(value.slice(0, end), "utf8") > maximum) end--;
  return value.slice(0, end);
}

export function truncateField(value: string, maximum: number, marker: string): string {
  if (Buffer.byteLength(value, "utf8") <= maximum) return value;
  const markerBytes = Buffer.byteLength(marker, "utf8");
  return utf8Prefix(value, Math.max(0, maximum - markerBytes)) + utf8Prefix(marker, maximum);
}

export function truncateOutput(value: string): string {
  const lines = value.split("\n");
  const lineLimited = lines.length > MAX_OUTPUT_LINES ? lines.slice(0, MAX_OUTPUT_LINES).join("\n") : value;
  const content = utf8Prefix(lineLimited, MAX_OUTPUT_BYTES);
  if (content === value) return value;
  const omittedBytes = Buffer.byteLength(value, "utf8") - Buffer.byteLength(content, "utf8");
  const omittedLines = Math.max(0, lines.length - content.split("\n").length);
  return `${content}\n\n[Output truncated: ${omittedBytes} bytes and ${omittedLines} lines omitted]`;
}

export function truncateStderr(value: string): string {
  const total = Buffer.byteLength(value, "utf8");
  if (total <= MAX_STDERR_BYTES) return value;
  let start = Math.max(0, value.length - MAX_STDERR_BYTES);
  while (start < value.length && Buffer.byteLength(value.slice(start), "utf8") > MAX_STDERR_BYTES) start++;
  return `[stderr truncated: ${total - Buffer.byteLength(value.slice(start), "utf8")} bytes omitted]\n${value.slice(start)}`;
}

export function truncateFailure(value: string): string {
  return truncateField(value, MAX_FAILURE_BYTES, "\n[failure truncated]");
}

export function fitDisplayEvent(event: DisplayEvent): DisplayEvent {
  let fitted: DisplayEvent;
  if (event.kind === "assistant") {
    fitted = { ...event };
  } else {
    fitted = {
      ...event,
      toolCallId: truncateField(event.toolCallId, 256, "[toolCallId truncated]"),
      toolName: truncateField(event.toolName, 256, "[toolName truncated]"),
    };
  }
  const serializedBytes = () => Buffer.byteLength(JSON.stringify(fitted), "utf8");
  if (serializedBytes() <= MAX_DISPLAY_EVENT_BYTES) return fitted;
  const marker = "\n[event truncated]";
  if (fitted.kind === "assistant") {
    const source = fitted.text;
    let budget = Math.max(0, Buffer.byteLength(source, "utf8") - (serializedBytes() - MAX_DISPLAY_EVENT_BYTES));
    do { fitted.text = truncateField(source, budget--, marker); } while (serializedBytes() > MAX_DISPLAY_EVENT_BYTES && budget >= 0);
  } else if (fitted.kind === "tool-start") {
    const source = fitted.argsPreview;
    let budget = Math.max(0, Buffer.byteLength(source, "utf8") - (serializedBytes() - MAX_DISPLAY_EVENT_BYTES));
    do { fitted.argsPreview = truncateField(source, budget--, marker); } while (serializedBytes() > MAX_DISPLAY_EVENT_BYTES && budget >= 0);
  }
  return fitted;
}

function finalText(message: any): string {
  if (message?.role !== "assistant" || !Array.isArray(message.content)) return "";
  return message.content.filter((part: any) => part?.type === "text").map((part: any) => String(part.text ?? "")).join("\n");
}

export function resolvePiInvocation(argv: readonly string[], execPath: string): { command: string; args: string[] } {
  const script = argv[1];
  if (script && !script.startsWith("/$bunfs/root/") && !script.startsWith("node:")) {
    return { command: execPath, args: [script] };
  }
  const executable = basename(execPath).toLowerCase();
  return /^(node|bun)(\.exe)?$/.test(executable)
    ? { command: "pi", args: [] }
    : { command: execPath, args: [] };
}

export const productionRunnerDependencies: RunnerDependencies = {
  spawn: (command, args, options) => nodeSpawn(command, args, options) as SpawnedProcess,
  mkdtemp,
  writeFile,
  rm,
  setTimer: setTimeout,
  clearTimer: clearTimeout,
  argv: process.argv,
  execPath: process.execPath,
  tempRoot: tmpdir(),
};

export function createRunner(deps: RunnerDependencies): Runner {
  return {
    async run(request: RunRequest): Promise<RunResult> {
      if (request.signal?.aborted) throw new Error("Subagent was aborted before start");
      const directory = await deps.mkdtemp(join(deps.tempRoot, "awf-pi-subagent-"));
      const promptPath = join(directory, `${request.role}.md`);
      try {
        await deps.writeFile(promptPath, request.systemPrompt, { encoding: "utf8", mode: 0o600 });
        const invocation = resolvePiInvocation(deps.argv, deps.execPath);
        const args = [...invocation.args, "--mode", "json", "-p", "--no-session",
          "--model", `${request.model.provider}/${request.model.id}`,
          "--thinking", request.thinkingLevel,
          "--tools", request.tools.join(","),
          "--append-system-prompt", promptPath,
          `Task: ${request.task}`];
        const events: DisplayEvent[] = [];
        let omittedEvents = 0;
        let sequence = 0;
        const usage = emptyUsage();
        let output = "";
        let stderr = "";
        let model: string | undefined;
        let modelChanged = false;
        let latestCacheHitRate: number | undefined;
        let childErrorMessage: string | undefined;
        let stopReason: string | undefined;
        let toolCount = 0;
        let toolFailureCount = 0;
        let buffer = "";
        let closed = false;
        let timer: ReturnType<typeof setTimeout> | undefined;
        let abortListener: (() => void) | undefined;
        let forcedFailure: { reason: "error" | "aborted"; message: string } | undefined;

        const result = await new Promise<RunResult>((resolve, reject) => {
          let child: SpawnedProcess;
          try { child = deps.spawn(invocation.command, args, { cwd: request.cwd, shell: false, stdio: ["ignore", "pipe", "pipe"] }); }
          catch (error) { reject(error); return; }
          let settled = false;
          const buildResult = (failed: boolean, failureMessage?: string): RunResult => ({
            output: truncateOutput(output || "(no output)"),
            stderr: truncateStderr(stderr),
            events: [...events],
            omittedEvents,
            usage,
            model,
            modelChanged,
            latestCacheHitRate,
            stopReason,
            toolCount,
            toolFailureCount,
            failed,
            failureMessage: failureMessage ? truncateFailure(failureMessage) : undefined,
          });
          const finish = (failed = false, failureMessage?: string): void => {
            if (settled) return;
            settled = true;
            if (timer !== undefined) deps.clearTimer(timer);
            if (request.signal && abortListener) request.signal.removeEventListener("abort", abortListener);
            resolve(buildResult(failed, failureMessage));
          };
          const publishUpdate = (): void => request.onUpdate?.({
            events: [...events], omittedEvents, usage: { ...usage }, model, modelChanged, latestCacheHitRate,
          });
          const childFailureSummary = (): string => {
            const parts = [
              childErrorMessage ? `Error: ${childErrorMessage}` : "",
              output ? `Output: ${output}` : "",
            ].filter(Boolean);
            return parts.join("\n") || "(no output)";
          };
          const appendDisplayEvent = (event: DisplayEventInput): void => {
            const fitted = fitDisplayEvent({ ...event, sequence: ++sequence } as DisplayEvent);
            events.push(fitted);
            if (events.length > MAX_DISPLAY_EVENTS) {
              omittedEvents += events.length - MAX_DISPLAY_EVENTS;
              events.splice(0, events.length - MAX_DISPLAY_EVENTS);
            }
            publishUpdate();
          };
          const processEvent = (line: string): void => {
            if (!line.trim()) return;
            let event: any;
            try { event = JSON.parse(line); }
            catch {
              forcedFailure = { reason: "error", message: `Malformed child event: ${truncateOutput(line)}` };
              child.kill("SIGTERM");
              timer = deps.setTimer(() => { if (!closed) child.kill("SIGKILL"); }, KILL_DELAY_MS);
              return;
            }
            if (event.type === "message_end" && event.message?.role === "assistant") {
              const current = event.message.usage;
              const input = current?.input ?? 0;
              const outputTokens = current?.output ?? 0;
              const cacheRead = current?.cacheRead ?? 0;
              const cacheWrite = current?.cacheWrite ?? 0;
              usage.input += input;
              usage.output += outputTokens;
              usage.cacheRead += cacheRead;
              usage.cacheWrite += cacheWrite;
              usage.cost += current?.cost?.total ?? 0;
              usage.turns++;
              const promptTokens = input + cacheRead + cacheWrite;
              latestCacheHitRate = promptTokens > 0 ? (cacheRead / promptTokens) * 100 : undefined;
              const reportedID = event.message.responseModel ?? event.message.model;
              const reportedModel = event.message.provider && reportedID
                ? `${event.message.provider}/${reportedID}`
                : reportedID;
              if (reportedModel) {
                if (model !== undefined && model !== reportedModel) modelChanged = true;
                model = reportedModel;
              }
              if (event.message.errorMessage) childErrorMessage = String(event.message.errorMessage);
              /* node:coverage ignore next -- defensive fallback; child assistant messages normally carry a stop reason */
              stopReason = event.message.stopReason ?? stopReason;
              const text = finalText(event.message);
              if (text) { output = text; appendDisplayEvent({ kind: "assistant", text }); }
              else publishUpdate();
            }
            if (event.type === "tool_execution_start") {
              toolCount++;
              appendDisplayEvent({ kind: "tool-start", toolCallId: String(event.toolCallId ?? ""), toolName: String(event.toolName ?? "tool"), argsPreview: JSON.stringify(event.args ?? {}) });
            }
            if (event.type === "tool_execution_end") {
              if (event.isError) toolFailureCount++;
              appendDisplayEvent({ kind: "tool-end", toolCallId: String(event.toolCallId ?? ""), toolName: String(event.toolName ?? "tool"), isError: Boolean(event.isError) });
            }
          };
          child.stdout.on("data", (chunk: Buffer | string) => {
            buffer += chunk.toString();
            const lines = buffer.split("\n");
            buffer = lines.pop() as string;
            for (const line of lines) processEvent(line);
          });
          child.stderr.on("data", (chunk: Buffer | string) => { stderr = truncateStderr(stderr + chunk.toString()); });
          child.once("error", (error) => finish(true, `Subagent process error: ${error.message}`));
          child.once("close", (code) => {
            closed = true;
            if (buffer.trim() && !forcedFailure) processEvent(buffer);
            if (forcedFailure) {
              stopReason = forcedFailure.reason;
              finish(true, forcedFailure.message);
            } else if (code !== 0) {
              stopReason = "error";
              const diagnostics = [childErrorMessage, truncateStderr(stderr)].filter(Boolean).join("\n") || "no diagnostics";
              finish(true, `Subagent exited ${code}: ${diagnostics}`);
            } else if (stopReason === "error" || stopReason === "aborted") {
              finish(true, `Subagent ${stopReason}: ${truncateOutput(childFailureSummary())}`);
            } else {
              finish();
            }
          });
          abortListener = () => {
            if (closed) return;
            forcedFailure = { reason: "aborted", message: "Subagent was aborted" };
            child.kill("SIGTERM");
            timer = deps.setTimer(() => { if (!closed) child.kill("SIGKILL"); }, KILL_DELAY_MS);
          };
          request.signal?.addEventListener("abort", abortListener, { once: true });
          if (request.signal?.aborted) abortListener();
        });
        return result;
      } finally {
        await deps.rm(directory, { recursive: true, force: true });
      }
    },
  };
}
